-- ─── Applied-migrations ledger check — READ ONLY, SINGLE RESULT SET ──────────
--
-- GENERATED by scripts/migration-ledger.mjs. Do not hand-edit — regenerate after adding
-- a migration.
--
-- Compares public.schema_migrations_applied against the 110 files currently in
-- supabase/migrations/. ZERO ROWS = every migration is applied and unedited since.
--
-- Requires the ledger to exist (supabase/migrations/20260903_migration_ledger.sql).
-- Kept separate from schema_drift_audit.sql so that audit still runs before the ledger
-- exists — a query naming a missing table fails at plan time, and plain SQL has no way
-- to make one section conditional.
--
-- SAFE: SELECT only.

WITH ondisk (filename, checksum) AS (VALUES
  ('20260621_provider_verification.sql', '931388cabb08b3689047f3f0794dd5c721dd78d939321e5af9a3bb54f2c17f2e'),
  ('20260623_cross_user_notifications.sql', 'f90fdb85692138af7582b66007a39d859d91ccfd10f9dd21a57d0b19e50b6f28'),
  ('20260628_search_content_rpc.sql', '1bb37c45a9421001d358d0dd64d4bb6a5fed92056a45203056ba89754e8ced1d'),
  ('20260701_rate_limits.sql', 'e8b84a9d38c2ff0046e32276473c898104a70a26c80fd846ddee948ae8f65b87'),
  ('20260701_security_fixes.sql', '71622f80cd2347b372d79d90241a9f768bef2fbcfea3f768b9f9d9d15d7eedeb'),
  ('20260702_job_postings.sql', 'b5e543498fe7b19a70bb7c9e866c82dc913838f78add2462d931f125cfa69684'),
  ('20260705_job_postings_auto_expire.sql', '8c7bb5affc8f91989bd05e5d1aa4ac08eb9b3fb7208795579d3b9515fa399e5e'),
  ('20260705_job_postings_rls_lockdown.sql', '6ee345b508f1a799961494c7bc9884de7ee70117f4788475d2c023482dfe2257'),
  ('20260705_search_content_add_jobs.sql', 'f15fc259fa1121f2c3372d8e3bcc3db88d54ea5e3b3f03bc25664ee3e9d04445'),
  ('20260712_ugc_moderation.sql', '833f149479c9b72d46966348691657668cf81e5762eea0e40027a9abb29d4fac'),
  ('20260712_ugc_moderation_fix_rate_limit.sql', 'b5d18c0c7f3bf28870a56f2ae295cdc8d224c98a50c2d74aa5f850799a6bf43a'),
  ('20260714_block_anonymous_writes.sql', '5d3ea78e6093769880e5a6f2726c020df9057524ca10725bf70fed6d8283ef92'),
  ('20260718_capture_1_tables_missing_from_repo.sql', 'ab90ecebc5ab99a569c98117478808a3ad74b465e96c3b26de649ae9c1f33947'),
  ('20260718_capture_2_check_constraints.sql', 'dc3965ac9370fb4a673d136c112fc3774d699c106f8a90a7c670e586201341e9'),
  ('20260718_capture_3_functions.sql', '4945df76902582a30a159d0908a68af7582152f49e673b50e9182f710d8c3443'),
  ('20260718_capture_4_triggers.sql', '37c648bdc891e316d98f02cc016c1725bc492e373980a1a4f6b153021740b5f3'),
  ('20260718_capture_5_rls_policies.sql', '63f95a0c29447a8787adc02f32456213083dbde8b4df7f06f2004fbfa3fd9c69'),
  ('20260718_events_allow_owner_submit.sql', '802c24344ead82f39a621bf87ad9df7e08618616c93e7fc0c2dc9a6d30a70b48'),
  ('20260718_facilities_guards.sql', '9a0289b727048a5a5ee2124cb2cd11bd07ad3e21640b17aa4926100254b20920'),
  ('20260719_add_missing_indexes.sql', 'f68c62fd1c464b23271d937d91fec1b27ad311bc272e85af87e481b62e07a912'),
  ('20260719_claim_evidence_and_guard.sql', 'ad81c83bb68c9f8a009e8face82f15c7748c1627786f7eca2d11ac01a13dc330'),
  ('20260719_claim_rename_and_tax_no.sql', '8cd9369b011ca47e126b0dd4532721fce99469307b078bb03ac1ba439905f27e'),
  ('20260719_create_facility_claim_rpc.sql', 'a53b4fc4761c12f9b48a0c8a6df46df75459a7f3e849088ab0be00e6a1eeccce'),
  ('20260719_facilities_insert_force_unclaimed.sql', '51f5cb62d70d47560654a2ba690cb1b85392cbf54734b25a3ff3b9f1ea7f949b'),
  ('20260719_facilities_insert_rls_allow_unclaimed.sql', '556e1fb9440a5ee2906dac49c5b7352a54240dc072334df22b9680f1f566304e'),
  ('20260719_fix_appointment_time_check.sql', 'fc6b212f1573ff211853dcf29ef2ea2038deecafa3800b37fcedd26c979990bc'),
  ('20260719_fix_signup_role_and_home_service.sql', '42bc01b6ad1ec9393d1e03ed81e6bd6b7bae73e77bdbaea87c476663d3b4af04'),
  ('20260719_pin_definer_search_path.sql', '3229243ab29f681e10cc511ad32bc49f5f1fbcb00c275182944deff0b7a09bca'),
  ('20260722_job_postings_business_paid_tier.sql', '55eb0ea5e13718f342f576ec14def6bd63047b513d080163413fd3db8cbf51ce'),
  ('20260723_insurance_companies.sql', '1c29a330944f3a3d5404e5cdc488fcec72f47d37f99d854a6e8bb0e020a73a83'),
  ('20260723_place_photo_credits.sql', '9d587dbc334fe16175e34cdc82267e14631f1f93c217ca88c68fea55a6304baf'),
  ('20260724_events_category_narrow.sql', '5d92ed2310fb34d8d7bd3afc4c5b9133086f8d4347f1744aec9f1bf6fc1fa4ae'),
  ('20260724_events_category_widen.sql', '3ccc366dce5b77116fd926e03695d733a78dc99af765bea24f5630e9222e3e4a'),
  ('20260725_appointments_double_booking_guard.sql', 'b3bb31a2922055520030a5737fe2c4a27225a26f19bf2208828df012ab330093'),
  ('20260725_esim_waitlist.sql', 'c7705ead941e0845038232c65e265a5c03494073b6ccee19cf66c1b6f84f77eb'),
  ('20260725_grooming_directory.sql', 'bb9483c82661b53992b4990288b269e72184559e15e2b3224d911dca3f4eae6f'),
  ('20260726_grooming_booking_lifecycle.sql', '63964e94c060b13d7ed84b2b481ebd1b9dd892172eaab8e56d232a2c8075e3b7'),
  ('20260731_garages_directory.sql', '2ce1e3fac9acf57c28fe612b3b4217fb6f72992f19dbcf4d33b821cb2ae84973'),
  ('20260801_appointments_service_type.sql', 'a868805c2f2a505bcd3b129c765ebf74d8c221deb1cc711b4e6c67256ed4e1ad'),
  ('20260802_facilities_guard_garage_edit.sql', 'd7fb42c7b6b4fc943604fa3a0a149a14027f9c952d1696b230e83f3c55116655'),
  ('20260802_garage_booking_details.sql', 'a69b2c7010dfb608780a2df45a95fd4640b589c34da95a3abc692ec45787403f'),
  ('20260802_update_garage_facility.sql', '2c2b7c0cbf1fddad0f22723e9d50709ad6039476f1c688eb8ba96e58c053245e'),
  ('20260803_facility_report_moderation.sql', '6ec883dad6bbf445b7882a5989c56a704dcfaf60eeb6452a7936aeeecf4976a5'),
  ('20260803_garage_booking_lifecycle.sql', '37c1cd0e80f39628fb01900ceb16baabe72ca78a9598bf8dfb295a3faefb7fb4'),
  ('20260803_grooming_owner_edit.sql', '008432fcea198c533ad81de0eab4fb9a3de551297383137a7507a203ccbfbb71'),
  ('20260804_grooming_multi_category.sql', 'd078480d6bc52bfbd5ff9260aafe5c5c74c4351fdf6bbdb970e55d4fe0d51f6e'),
  ('20260805_facilities_city.sql', '14786a6fa4551d050e307bd89382fcadd268936ff063940a14561b9e55d9777c'),
  ('20260806_facilities_area.sql', 'fae38c643355292e78eca98656d05c46768b576268e3ee238c8af8660c23269a'),
  ('20260807_facility_content_filter.sql', 'ab86c9bca929b23250326bf050554b8efcf52aae69b1d125592b636386f4cb05'),
  ('20260808_facility_featured_tier.sql', '4e6e21fc2b6117869a594ec1088d7da2150e2bfd1ac91b84949424e1cde74be4'),
  ('20260809_featured_expiry_reminder.sql', '106ac108ae87128352e0d9cbee5b994ae5339f91a08e9c40e4ac4d26aeb7a5d4'),
  ('20260810_change_request_content_filter.sql', 'dd2785c9be0e69a6df7f077917b27d7d2d09b30390e53bc0e4397ddbe5726779'),
  ('20260811_facilities_service_prices.sql', 'a1bf769dbc95ea65147ebe5676b84f7a6807c0179727755fa7d024d9f37e11f5'),
  ('20260812_module_waitlist.sql', 'ab08e4010699b64b0a8e563f30b9279c3cfffc3e5a04d1d07a11ca799e79bead'),
  ('20260813_notify_module_waitlist.sql', '945f55477370fe848b214556edc37d6dec9d5ed407b1df954f69881229f8ac4f'),
  ('20260814_module_waitlist_add_studenthub.sql', 'ecc65943b7626e1ad546d490aab023b8b1f94ceb27cae2d69e1a0a5e72f0d14e'),
  ('20260815_questions_block_blocked_customers.sql', 'e27b25a849d914c7efa243641df1e8ee57a48240b3aab08908e9827925b963b6'),
  ('20260816_provider_storage_policies.sql', '003b4252191abd68f1e9d51d386e16b04fd65feac97f6b8e3bf0dfa1626610e6'),
  ('20260817_tighten_loose_storage_inserts.sql', '147f46facb170e6b843c032d464efa6e9f32d3a12dd6218a2e95307f2859c3dc'),
  ('20260818_preferred_language_nullable_default.sql', 'ad879a2d2bbe2bcd8e902a1d826e884819b6cfb88f8a64ae73ed6a2d18929edf'),
  ('20260819_get_customer_contacts_rpc.sql', '76eb5c4871df68f3c22453f35fbb6b831133e58ccc510960f93c74dfa896f742'),
  ('20260819_record_no_show_time_guard.sql', 'ba74ebf6ee0344afda8435c909aca711ef3a39ea48682fdde064ad38ed7781b6'),
  ('20260820_facilities_moderation_read_policy.sql', '975c9f29dac071c5dbca8a82533f4e9147d64abb370668d4d4bb07e573a5ed15'),
  ('20260820_search_content_gate_facilities.sql', 'cd2e21fafb3eed612f97a21ebafa49024e2f77eaeb306dfb659896c1d416f6bc'),
  ('20260821_drop_providers_read_customer_policy.sql', '7f9607fea36de1b3e4fc00261ab99d673854a1115994f2ad04ba69ad255bbcb8'),
  ('20260822_places_consolidation.sql', 'be1a39cd747e3b8942b8cf05b82ad9a910b1c687e358b3ca1be2a8f44cf43787'),
  ('20260823_place_photos_storage_policies.sql', '8ebb5e0eef06e58c9723ed9a77a12d33575402caf2c6d880c19cb3475419cfdd'),
  ('20260824_place_moderation.sql', '0953d68710cf01b709fba0e3a7eb80b8eb8cf2958e7c30986b6919201be78324'),
  ('20260825_places_column_guards.sql', '287fe4499da9e33f0a3e4f23e324eca8da46f5d59665b0d2660f95b11be4f838'),
  ('20260826_place_claims.sql', '8d0db056d47bede3cd4eea1c6d2dec61af2beb7ae7db1de073566efc0f1e0ce7'),
  ('20260827_places_featured_tier.sql', '0d5dc0c5fc2c0fea358f1f9f32662fb3642f915dfa716d648ae6a40de95e7674'),
  ('20260827_signup_customer_only.sql', '06126e0df0838af6e2ba149d9d339a2271d08be5e2abbeefdfda8b9c77a20fd5'),
  ('20260828_explore_waitlist_module.sql', 'f4c99b2eaf3a7c28288e6a080341722cbf2e272accf7977458d85f4731d5fbc7'),
  ('20260829_place_resubmit.sql', '166d8a5034f6958fc25e2ee6f9d6a6717f3d9684c804136d3dbfa1da958e9ca4'),
  ('20260830_events_gisekibris_import.sql', 'ad14c7c24327caa4f43c96bee648fe5d6fb8a994077869f0cbfc76a4ef200c7b'),
  ('20260831_events_external_id_remap.sql', '61ae1338ccb28cfc74ae484a5b2fc6af37afea9480fcc693983550cf0be3197e'),
  ('20260901_events_status_not_null.sql', '0bbac7857969d462d61a198c1e2d7f4588bd5657aeffc094f1402f0a758c4a46'),
  ('20260902_capture_schema_drift.sql', 'd3c3a233da2e99b5f042b944a1b557c4005e015d4d7aa0e1562f59f57189db82'),
  ('20260904_accommodation_partner_feed.sql', '3d67911cde0363e47b6ae56aaab81a442362b3ed05f48a2915c1a0f6b96337a0'),
  ('20260905_towing_companies.sql', 'e35c96f6c0c2e8abb29ce79f613d533a356e41de6523b3c18bffc9225d1c31a4'),
  ('20260906_search_content_add_towing.sql', '12857e3f341d06e753bf310af9269883c0f1f06db65751825b07f2b15073bf0e'),
  ('20260907_towing_is_active_default_false.sql', 'f284f684eb3d7094e1a3c26a51808af70f65e5e301c05782966b79e9dd180f98'),
  ('20260908_towing_phone_secondary.sql', 'ac45c7b0ac330781ecc014ab217ab58e81e6cc9744c830c6d969ec20ff2065a6'),
  ('20260909_notify_waitlist_add_modules.sql', '5c7d12c47f367e45562f98c71cb7a9a48d3070eff0295e391bdbf69d01ebe05c'),
  ('20260910_contact_events.sql', '6943b7a33ca0d2f732e7b6376a05fdcd89be031345f7360e731a079f89ce2b59'),
  ('20260911_facilities_public_health.sql', '04c9426ca0e99a6308a2ba433da1243ee814c882cdec48fb0d6b642409608a67'),
  ('20260912_search_tokenised_and_public_health_slice2.sql', 'a6b35cfa9a7197be00f386a6a80cdc95aed1e66567d9a92db33900c71e88fdf0'),
  ('20260913_public_health_contact_hygiene.sql', '2ca7c7b66c1054a68e1d411ae63a8f339570917812e3b354808729bcbeafef3a'),
  ('20260914_public_health_coordinates.sql', '4720cb19fc79708c11e793b8eee4e149569abe64155a17baffdbdbd42b7dbc46'),
  ('20260915_properties_deed_type_comment.sql', '175250865182c5d97b3a1d0da55caa0c05fcc13c4c57d55c4c82328eef5ac7a8'),
  ('20260916_novest_agency_and_seed_teardown.sql', 'aedbb300e2e9087414a6f082ea4e040da30233c19b36badce697f2b61748336f'),
  ('20260917_place_photo_attribution.sql', '4d3391d3d46f01b149296413f7a404475b768ec091d4d0237ba68cd2f8a1b071'),
  ('20260918_notify_waitlist_add_checkins.sql', '41374e31e529eb790597629778e33cb85a507248232944e8d7f15873d8bfdd95'),
  ('20260919_facilities_geocode_provenance.sql', '9a19cd36db709437bb270b0aa7605732be0f855de39c04d6d74d305e27995683'),
  ('20260920_duty_list_idempotent_load.sql', '4fd6dad866b0e1a641f0f2977788332546b6a0795ccbac96d73c883cfde10e24'),
  ('20260921_place_claims_category_guard.sql', '3d6e024d02c54243dc5d880a8e5b7c3efcbab31c33efd4b1b879237aecad0657'),
  ('20260922_drop_grooming_profile_overshare.sql', 'c582a3ae15cb4ab68224ec18399d1a9416a5705a98ea2ee833f5375505c2d2a4'),
  ('20260923_server_side_notifications.sql', 'a11cab7b6e4d6780152dc2104b64a3789786d78ee4001596f7784080a323d6a1'),
  ('20260924_search_content_hide_unclaimed_pharmacies.sql', 'd81636e62f8583ca061bfd0b81774792260ea19cf2bb736243750c08fc126a14'),
  ('20260925_moderation_normalization.sql', 'f0fb8563f3279dccd9b030a19f5883d291b80f0c8b146d6458f935fba260fcba'),
  ('20260926_moderation_rejection_log.sql', 'f3272ba20c48dd95750f645cdf5e2b1ab05e55623d86e5066fa1259531699a71'),
  ('20260927_admin_ugc_update_policies.sql', '7b2cd64f952c7ba1705aeb815bc7a3e0525e3eb790d4053cf725ad4d1539e705'),
  ('20260928_ugc_soft_delete.sql', '23a9cace46d7e7bae843132067621b5ca0056640bd12c9dd0ba3b44588e3c20a'),
  ('20260929_reviews_appointment_unique_partial.sql', 'df13e7342f50a3893e1b039b7ab8799176d705f026bc52fe39505d1cecdff69a'),
  ('20260930_answers_read_gates.sql', '3088c605e4657b1057569a851b6f0037b21bdfe3eb5cab8a78f250c390ab8fa1'),
  ('20261001_profile_completion_schema.sql', '6584b8acd688efb434ae2174b44727a1f9865936aa7cf6bbd4799ed0b763f55b'),
  ('20261002_display_name_availability_rpc.sql', '2fd15ce7bc48777128cfbcbb5cede8b39f6428413ef28fef9be5b647c3718dad'),
  ('20261003_reviews_decouple_from_appointments.sql', '83d26092769eff887ed4660a7eec29d423d3b65a52c45f4d398f8f66b543d19f'),
  ('20261004_appointments_removal.sql', 'c3e4f3caa159ac5af760e6e6ef805b4f9f58406412ffcf0ca134ccefa97137e3'),
  ('20261005_geocode_corroboration_name_match.sql', '772db18cb37c22a32030bc50e30d67415ac14b09f9a6e05f071359bb7ece6742')
)
SELECT * FROM (
  -- NEVER APPLIED — committed and forgotten. Apply it, or delete the file.
  SELECT 'L1-never-applied' AS section, d.filename AS c1,
         'no ledger row' AS c2, '' AS c3
  FROM ondisk d
  WHERE NOT EXISTS (SELECT 1 FROM public.schema_migrations_applied l
                    WHERE l.filename = d.filename)

  UNION ALL
  -- EDITED AFTER APPLYING — the file on disk is not what ran. The case nothing could
  -- previously detect. A baseline row differing here means the file changed since
  -- 2026-08-19; re-verify against live before trusting either side.
  SELECT 'L2-checksum-mismatch', d.filename,
         'ledger ' || left(l.checksum, 12) || '…  disk ' || left(d.checksum, 12) || '…',
         'applied_by=' || l.applied_by || ' at ' || l.applied_at::date
  FROM ondisk d
  JOIN public.schema_migrations_applied l ON l.filename = d.filename
  WHERE l.checksum <> d.checksum

  UNION ALL
  -- IN THE LEDGER, NOT ON DISK — a migration file was deleted or renamed after being
  -- applied. Not necessarily wrong, but the repo no longer describes something that ran.
  SELECT 'L3-ledger-orphan', l.filename,
         'file absent from supabase/migrations/', 'applied ' || l.applied_at::date
  FROM public.schema_migrations_applied l
  WHERE NOT EXISTS (SELECT 1 FROM ondisk d WHERE d.filename = l.filename)
    AND l.filename <> '20260903_migration_ledger.sql'
) r
ORDER BY section, c1;
