export const SPECIALTIES_BY_TYPE = {
  clinic: [
    'General Practice',
    'Physiotherapy',
    'Dietitian & Nutrition',
    'Dermatology',
    'Cardiology',
    'Orthopedics',
    'Pediatrics',
    'Gynecology & Obstetrics',
    'Ophthalmology',
    'ENT',
    'Psychology & Mental Health',
    'Neurology',
    'Urology',
    'Rheumatology',
    'Endocrinology',
  ],
  hospital: [
    'General Hospital',
    'Emergency & Trauma',
    'Maternity',
    'Surgical',
    'Oncology',
  ],
  pharmacy: [
    'General Pharmacy',
    'Compounding Pharmacy',
    'Veterinary Pharmacy',
  ],
  dentist: [
    'General Dentistry',
    'Orthodontics',
    'Oral Surgery',
    'Pediatric Dentistry',
    'Dental Implants',
    'Periodontics',
  ],
}
