-- 387 pharmacies from KTEB official list
-- Run in Supabase SQL editor
INSERT INTO facilities (name, type, address, phone, is_public, provider_id, contact_person) VALUES
('ABBASOĞLU ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Cad. No: 112/D, Küçük Kaymaklı, Lefkoşa', '(0392) 227 16 64', true, null, 'Ecz. İsmet Abbasoğlu'),
('ADAHAN ECZANESİ', 'pharmacy', 'Gaz. Kemal Aşık Cad. No:17, Küçük Kaymaklı, Lefkoşa', '(0392) 227 37 00', true, null, 'Ecz. Duygu Adahan Kuran'),
('AHMET MISIRLI ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad. 42/6, Kermiya, Lefkoşa', '(0392) 223 93 93', true, null, 'Ecz. İldem Mısırlı'),
('AKDENİZ ECZANESİ', 'pharmacy', 'Atatürk Caddesi, Yenişehir, Lefkoşa', '(0392) 228 82 77', true, null, 'Uzm. Ecz. Umay Öksüz Üstün'),
('AKDORA ECZANESİ', 'pharmacy', 'Mumcu Tepe Sos. Anıttepe, Hamitköy, Lefkoşa', '(0392) 225 33 55', true, null, 'Ecz. Meliz Akdora'),
('ALİ ERSOY ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad. No: 65, Metehan, Lefkoşa', '(0392) 330 12 77', true, null, 'Ecz. Ali Ersoy'),
('ALPDOĞAN ECZANESİ', 'pharmacy', 'Nazım Hikmet Cad. No: 124/4, Metehan, Lefkoşa', '(0392) 330 10 36', true, null, 'Ecz. Nejmi Alpdoğan'),
('APAYDIN ECZANESİ', 'pharmacy', '2. Selim Cad., Köşlüçiftlik, Lefkoşa', '(0392) 227 51 59', true, null, 'Ecz. Duygu Akova'),
('ARASTA ECZANESİ', 'pharmacy', 'Şht. Eybil H. Çetin Sokak No: 14, Arasta Çarşısı, Lefkoşa', '(0548) 837 44 65', true, null, 'Ecz. Simge Sonap'),
('ARDA ULUPINAR ECZANESİ', 'pharmacy', 'Bedrettin Cad., Kuzey Kavşağı No: 4, Lefkoşa', '(0533) 824 00 64', true, null, 'Ecz. Arda Ulupınar'),
('ARZUM DAVULCU ECZANESİ', 'pharmacy', 'Şht. Mustafa Yusuf Hacı Sok. No: 3, Yenişehir, Lefkoşa', '(0392) 227 14 57', true, null, 'Ecz. Arzum Davulcu'),
('ATAER ECZANESİ', 'pharmacy', 'Şht. Zehra Mustafa Sokak No: 5, Gönyeli, Lefkoşa', '(0392) 223 14 85', true, null, 'Ecz. İlayda Sebatlı'),
('AYŞE BIYIKOĞLU ECZANESİ', 'pharmacy', 'Yeşilyurt Sokak, Yenikent, Gönyeli, Lefkoşa', '(0392) 223 67 50', true, null, 'Ecz. Ayşe Bıyıkoğlu'),
('AYŞE KETEN ECZANESİ', 'pharmacy', 'Sakarya Sok. No:18, Alayköy, Lefkoşa', '(0392) 235 77 22', true, null, 'Ecz. Ayşe Keten'),
('AZİZ GÜZELER ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Caddesi, Ortaköy, Lefkoşa', '(0548) 856 36 82', true, null, 'Ecz. Aziz Güzeler'),
('BAHAR NURLUÖZ ECZANESİ', 'pharmacy', 'Hacet Sok. No:8, Hamitköy, Lefkoşa', '(0392) 225 61 61', true, null, 'Ecz. Bahar Nurluöz'),
('BAHİRE ÖZSU AKDOĞAN ECZANESİ', 'pharmacy', 'Ali Rıza Efendi Cd., Ortaköy, Lefkoşa', '(0533) 830 84 70', true, null, 'Ecz. Bahire Özsu Akdoğan'),
('BALIN ECZANESİ', 'pharmacy', 'Dr. Burhan Nalbantoğlu Cad., Lefkoşa', '(0392) 223 18 13', true, null, 'Ecz. Eda Tülek'),
('BEHAYİ YILMABAŞAR ECZANESİ', 'pharmacy', 'Okullar Yolu Sokak No: 66A, Küçük Kaymaklı, Lefkoşa', '(0392) 227 11 16', true, null, 'Ecz. Behayi Yılmabaşar'),
('BERİL ECZANESİ', 'pharmacy', 'Müftü Ziayi Efendi Sok. No 28B, Lefkoşa', '(0392) 227 73 10', true, null, 'Ecz. Beril Çakır'),
('BERİLAL ECZANESİ', 'pharmacy', 'Atatürk Cad. No:21, Lefkoşa', '(0392) 228 00 16', true, null, 'Ecz. Alev Çakır'),
('BERKE SEMERCİ ECZANESİ', 'pharmacy', 'Metropol yolu, Taşkınköy, Lefkoşa', '(0533) 832 95 60', true, null, 'Ecz. Berke Ali Semerci'),
('BİLGE TÜRKSEVEN ECZANESİ', 'pharmacy', 'Küçük Kaymaklı, Lefkoşa', '(0539) 118 31 43', true, null, 'Ecz. Bilge Türkseven'),
('BİRGÜN ECZANESİ', 'pharmacy', 'Kemal Aksay Cad. No: 36, Taşkınköy, Lefkoşa', '(0392) 225 24 12', true, null, 'Ecz. Fatma Şentürk'),
('BUSE AVCI ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Caddesi, Küçük Kaymaklı, Lefkoşa', '(0392) 227 46 87', true, null, 'Ecz. Gül Buse Avcı'),
('BUSE KARŞILI ECZANESİ', 'pharmacy', 'Demir Sok., Yenikent, Lefkoşa', '(0392) 224 15 45', true, null, 'Ecz. Buse Karşılı'),
('ÇAĞANSOY ECZANESİ', 'pharmacy', 'Kenan Evren Cad., Yenikent, Gönyeli, Lefkoşa', '(0392) 223 67 66', true, null, 'Ecz. Zehra Çağansoy'),
('ÇAĞIN KORKMAZER ECZANESİ', 'pharmacy', 'Atatürk Cad. No:17/A, Yenişehir, Lefkoşa', '(0392) 228 09 09', true, null, 'Dr. Ecz. Çağın Korkmazer'),
('ÇAĞLAYAN ECZANESİ', 'pharmacy', 'İffet Oruz Sok., Çağlayan, Lefkoşa', '(0392) 227 61 81', true, null, 'Ecz. Mine Akkoyun'),
('ÇAĞRI CANDANAL ECZANESİ', 'pharmacy', 'Şht. Hüseyin Amca Cad., Gönyeli, Lefkoşa', '(0548) 880 70 70', true, null, 'Ecz. Çağrı Tansel Okuyucu Candanal'),
('CANEŞ ECZANESİ', 'pharmacy', 'Şht. Mustafa Mehmet Sok., Taşkınköy, Lefkoşa', '(0392) 225 52 20', true, null, 'Ecz. Caneş Tatlıcıoğlu'),
('CANKAN ECZANESİ', 'pharmacy', 'Mehmet Akif Caddesi No: 91, Kumsal, Lefkoşa', '(0392) 229 01 28', true, null, 'Ecz. Elif Altuncuoğlu'),
('ÇELER ECZANESİ', 'pharmacy', 'Hazar Sok. No:19, Lefkoşa', '(0392) 225 75 05', true, null, 'Ecz. Bahire Çeler'),
('CEMALİYE AĞAOĞLU ECZANESİ', 'pharmacy', 'Raif Denktaş Cad. No: 37, Göçmenköy, Lefkoşa', '(0533) 874 14 05', true, null, 'Ecz. Cemaliye Ağaoğlu'),
('CEMİL BEY ECZANESİ', 'pharmacy', 'Atatürk Cad. No:85, Alayköy, Lefkoşa', '(0533) 838 01 45', true, null, 'Ecz. Ali Şensoy'),
('CEMİLE FIRINCIOĞLULARI ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad. 81/C, Ortaköy, Lefkoşa', '(0392) 223 82 22', true, null, 'Ecz. Cemile Fırıncıoğluları'),
('CEMRE ECZANESİ', 'pharmacy', 'Marmara Bölgesi 30. Sok. No: 1, Lefkoşa', '(0392) 227 65 49', true, null, 'Ecz. Cemil Fahrioğlu'),
('CEVHER ECZANESİ', 'pharmacy', 'Mehmet Akif Cad. 101/E, Dereboyu, Lefkoşa', '(0392) 227 72 51', true, null, 'Ecz. Cevher Cem'),
('ÇINARLI ECZANESİ', 'pharmacy', 'Güven Sok. 21A, Hamitköy, Lefkoşa', '(0392) 225 23 60', true, null, 'Ecz. Nezire Çınarlı'),
('ÇİSE YILDIRIM ECZANESİ', 'pharmacy', 'Marmara Bölgesi 4. Sokak No: 5, Lefkoşa', '(0539) 106 52 86', true, null, 'Ecz. Çise Yıldırım'),
('DAĞMAN ECZANESİ', 'pharmacy', 'Aliriza Efendi Cad., Ortaköy, Lefkoşa', '(0533) 847 03 63', true, null, 'Ecz. Gökcen Dağman'),
('DAMLA KARDÜZ ECZANESİ', 'pharmacy', 'Atatürk Cad., Gönyeli, Lefkoşa', '(0392) 223 45 65', true, null, 'Ecz. Damla Kardüz Özalkın'),
('DENİZ ÇORBA ECZANESİ', 'pharmacy', 'Belediye Bulvarı 91/B, Yenikent, Lefkoşa', '(0392) 223 72 72', true, null, 'Ecz. Deniz Çorba'),
('DEREBOYU ECZANESİ', 'pharmacy', 'Mehmet Akif Cad. No: 51/2, Köşklüçiftlik, Lefkoşa', '(0533) 839 14 14', true, null, 'Ecz. Dilan Şengül'),
('DİDEM ÖZKAYALI ECZANESİ', 'pharmacy', '2. Selim Caddesi, Köşklüçiftlik, Lefkoşa', '(0392) 227 71 11', true, null, 'Ecz. Didem Özkayalı'),
('DİLAY KILÇIK ECZANESİ', 'pharmacy', 'Şht. Cumhuryüzlü Sokak, Ortaköy, Lefkoşa', '(0392) 330 00 89', true, null, 'Ecz. Dilay Kılçık'),
('DİLAY MENEKAY ECZANESİ', 'pharmacy', 'Osman Paşa Caddesi No: 43/C, Köşlüçiftlik, Lefkoşa', '(0539) 103 42 22', true, null, 'Ecz. Eşmene Dilay Menekay'),
('DİLEK ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Cad. No:107, Kızılbaş, Lefkoşa', '(0392) 228 18 67', true, null, 'Ecz. Dilek Taçoy'),
('DİLEM UZCAN ECZANESİ', 'pharmacy', 'Şht. Hüseyin Amca Caddesi, Gönyeli, Lefkoşa', '(0548) 850 80 58', true, null, 'Ecz. Dilem Uzcan'),
('DİMAY KAĞCAN ECZANESİ', 'pharmacy', '9. Yavuz Konnolu Sok., Ortaköy, Lefkoşa', '(0392) 223 86 75', true, null, 'Ecz. Dimay Kağcan'),
('EBRU BAŞAY ECZANESİ', 'pharmacy', 'Mehmet Akif Cad. No: 78/3, Dereboyu, Lefkoşa', '(0392) 227 02 42', true, null, 'Ecz. Ebru Başay'),
('EDA ENVER ECZANESİ', 'pharmacy', 'Şht. Arseven Sk. No:6, Lefkoşa', '(0392) 223 48 10', true, null, 'Ecz. Eda Enver Zaim'),
('EMEL ATAÇAĞ ECZANESİ', 'pharmacy', 'Atatürk Cad. No: 65, Gönyeli, Lefkoşa', '(0392) 224 06 11', true, null, 'Ecz. Emel Ataçağ'),
('EMİNE KESKİN ECZANESİ', 'pharmacy', 'Atatürk Cad., Gönyeli, Lefkoşa', '(0533) 879 81 93', true, null, 'Ecz. Emine Keskin'),
('ENVER ECZANESİ', 'pharmacy', 'Atatürk Meydanı 74, Lefkoşa', '(0392) 227 25 67', true, null, 'Ecz. Enver Emin Özbeşer'),
('EREN ECZANESİ', 'pharmacy', 'Şht. Kemal Ünal Cad. No: 53, Taşkınköy, Lefkoşa', '(0392) 225 24 74', true, null, 'Ecz. Ceyda Neriman Eren'),
('ERSAĞ ECZANESİ', 'pharmacy', 'Fuar Yolu üzeri, Lefkoşa', '(0392) 223 62 17', true, null, 'Ecz. Hasan Özerk'),
('ERTUNGA ECZANESİ', 'pharmacy', 'Marmara Bölgesi 4. Sokak No: 19, Lefkoşa', '(0533) 875 56 06', true, null, null),
('FATMA AŞİNA ECZANESİ', 'pharmacy', 'Aliriza Efendi Cad. No: 38/D, Ortaköy, Lefkoşa', '(0533) 883 22 96', true, null, 'Ecz. Fatma Aşina'),
('FATMA TAHSİN ECZANESİ', 'pharmacy', 'Atatürk Cd. 107B, Gönyeli, Lefkoşa', '(0392) 224 09 00', true, null, 'Ecz. Fatma Tahsin'),
('FATMA YÜRÜN ECZANESİ', 'pharmacy', 'Bolu Sok. No: 74/C, Küçük Kaymaklı, Lefkoşa', '(0392) 227 10 80', true, null, 'Ecz. Fatma Yürün'),
('FERİN ECZANESİ', 'pharmacy', 'Cebeci Sok. No:35, Yenikent, Gönyeli, Lefkoşa', '(0392) 223 42 82', true, null, 'Ecz. Dicle Tekiner'),
('FİRUZ ERGİL ECZANESİ', 'pharmacy', 'Yakındoğu Bulvarı 40/D, Taşkınköy, Lefkoşa', '(0392) 223 19 02', true, null, 'Ecz. Firuz Ergil'),
('FULDEN DONANGİL ECZANESİ', 'pharmacy', 'Osman Paşa Cad. No:29/B, Köşlüçiftlik, Lefkoşa', '(0392) 228 25 72', true, null, 'Ecz. Fulden Donangil'),
('GALEN ECZANESİ', 'pharmacy', 'Kemal Aşık Cad. 62/1, Küçük Kaymaklı, Lefkoşa', '(0392) 227 26 03', true, null, 'Ecz. Bahire Turganer'),
('GİZEM BEHLÜL ECZANESİ', 'pharmacy', 'Atatürk Cad., Gönyeli, Lefkoşa', '(0392) 223 45 75', true, null, 'Ecz. Gizem Behlül'),
('GÖNÜL ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad., Ortaköy, Lefkoşa', '(0392) 227 84 61', true, null, 'Ecz. Gönül Akça'),
('GÖNYELİ ECZANESİ', 'pharmacy', 'Ünveren Sok., Yenikent, Gönyeli, Lefkoşa', '(0533) 856 64 44', true, null, 'Ecz. Kezban Doygunel'),
('GÜLİSTAN ARICI ECZANESİ', 'pharmacy', 'Hasane Ilgaz 13/C, Köşlüçiftlik, Lefkoşa', '(0533) 841 28 39', true, null, 'Ecz. Gülistan Arıcı'),
('GÜLİZAR ÖZTEKNİK ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Cad., Küçük Kaymaklı, Lefkoşa', '(0392) 227 91 55', true, null, 'Ecz. Gülizar Özteknik'),
('GÜLNUR ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad., Metehan, Lefkoşa', '(0392) 223 66 30', true, null, 'Ecz. Gülnur Çelik'),
('GÜNEY ENGİNOL ECZANESİ', 'pharmacy', 'Yzb. Tekin Yurdabak Caddesi No: 25, Ortaköy, Lefkoşa', '(0392) 227 66 95', true, null, 'Ecz. İltem Enginol Demirci'),
('HALKSEVER ECZANESİ', 'pharmacy', 'Şht. Hüseyin Amca Cad. No:97, Gönyeli, Lefkoşa', '(0392) 223 10 50', true, null, 'Ecz. Enver Halksever'),
('HARİKA OTAĞ ECZANESİ', 'pharmacy', 'Cebeci Sok. 25, Yenikent, Gönyeli, Lefkoşa', '(0392) 224 04 15', true, null, 'Ecz. Harika Otağ'),
('HAYAT ECZANESİ', 'pharmacy', 'Girne Cad. Vakıflar Çarşısı No:2, Lefkoşa', '(0392) 227 51 26', true, null, 'Ecz. Ersel Tüccaroğlu'),
('HAZAL REİS ECZANESİ', 'pharmacy', 'İplik Pazarı, Surlariçi, Lefkoşa', '(0533) 840 15 12', true, null, 'Ecz. Hazal Reis'),
('HÜSEYİN KERİM SAKALLI ECZANESİ', 'pharmacy', 'Şht. Yzb. Tekin Yurdabak Cad., Ortaköy, Lefkoşa', '(0392) 228 46 00', true, null, 'Ecz. Hüseyin Kerim Sakallı'),
('İMGE ECZANESİ', 'pharmacy', 'Yaman Bey Sokak No: 8, Göçmenköy, Lefkoşa', '(0392) 223 59 51', true, null, 'Ecz. Halit Kavçın'),
('İNANLI ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Cad., Küçük Kaymaklı, Lefkoşa', '(0392) 227 23 90', true, null, 'Ecz. Ali İnanlı'),
('İNCİRLİ ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad. 46/A, Aydemet, Lefkoşa', '(0392) 330 20 22', true, null, 'Ecz. Gülçin İncirli'),
('IŞIK KEREM ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad. No: 37/A, Aydemet, Lefkoşa', '(0533) 826 48 02', true, null, 'Ecz. Işık Kerem'),
('İSMET ECZANESİ', 'pharmacy', 'Bedreddin Demirel Caddesi No: 92, Lefkoşa', '(0392) 228 15 40', true, null, 'Ecz. İsmet Abohorlu'),
('İZEM ECZANESİ', 'pharmacy', 'İsmail Beyoğlu Cad. 44/A, Küçük Kaymaklı, Lefkoşa', '(0392) 228 00 40', true, null, 'Ecz. İzem Özvurulmuş'),
('KAPTAN CAN ECZANESİ', 'pharmacy', 'Dokuz Yavuz Konnolu Sokak No: 11B, Ortaköy, Lefkoşa', '(0548) 853 54 78', true, null, 'Ecz. Can Kaptan'),
('KERMİYA ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad. No:24, Metehan, Lefkoşa', '(0392) 223 34 83', true, null, 'Ecz. Mehmet Dümenci'),
('KEZİBAN TİLKİ ECZANESİ', 'pharmacy', 'Atatürk Cad., Gönyeli, Lefkoşa', '(0392) 223 12 10', true, null, 'Ecz. Keziban Tilki'),
('KIZILBAŞ ECZANESİ', 'pharmacy', 'Kemal Aksay Cad. No: 43/2, Taşkınköy, Lefkoşa', '(0392) 225 32 59', true, null, 'Dr. Ecz. Hasan İsfendiyaroğlu'),
('KUZEY ECZANESİ', 'pharmacy', 'Raif Denktaş Cad. No:35/5, Göçmenköy, Lefkoşa', '(0533) 868 33 37', true, null, 'Ecz. Dilek Bulut'),
('LA PHARMA ECZANESİ', 'pharmacy', 'Şht. Mustafa Mehmet Sok. 71/C, Göçmenköy, Lefkoşa', '(0392) 223 14 14', true, null, 'Ecz. Arda Özyol'),
('LADEN AKBATUR ECZANESİ', 'pharmacy', 'Selçuklu Cad. No:46, Lefkoşa', '(0392) 227 25 75', true, null, 'Ecz. Laden Akbatur'),
('LAİKA GÖKÇEKUŞ ECZANESİ', 'pharmacy', 'Belediye Bulvarı No:3713, Yenikent, Gönyeli, Lefkoşa', '(0392) 224 09 88', true, null, 'Ecz. Laika Gökçekuş'),
('LEFKOŞA ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Caddesi No: 13/B, Yenişehir, Lefkoşa', '(0548) 825 19 03', true, null, 'Ecz. Vijdan Baysal'),
('MALEK ECZANESİ', 'pharmacy', 'Yzb. Tekin Yurdabak Cad., Marmara Bölgesi, Lefkoşa', '(0392) 227 92 70', true, null, 'Ecz. Yağmur Malek'),
('MERVE BİLLUR ECZANESİ', 'pharmacy', 'Atatürk Cad., Gönyeli, Lefkoşa', '(0392) 223 43 50', true, null, 'Ecz. Merve Billur'),
('MİEL ECZANESİ', 'pharmacy', 'Aydemet Mahallesi, Nazım Hikmet Cad. No: 46/B, Lefkoşa', '(0542) 889 00 09', true, null, 'Ecz. Selma Soylukal'),
('MOR SAFİR ECZANESİ', 'pharmacy', 'Şht. Halil Mustafa Sokak, Lefkoşa', '(0533) 113 83 12', true, null, 'Ecz. Dursun Emre Duran'),
('MUSTAFA GÜRMAN ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad. No: 6/B, Kermiya, Lefkoşa', '(0392) 330 08 30', true, null, 'Dr. Ecz. Mustafa Gürman'),
('MUSTAFA PEHLİVAN ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Cad. No: 88, Kızılbaş, Lefkoşa', '(0392) 228 71 07', true, null, 'Ecz. Mustafa Pehlivan'),
('NECATİBEY ECZANESİ', 'pharmacy', 'Osman Paşa Cad. No: 9/7, Köşlüçiftlik, Lefkoşa', '(0392) 228 14 78', true, null, 'Ecz. Ayfer Uzman'),
('NECLA EMİN ECZANESİ', 'pharmacy', 'Rıza Vuruşkan Sok. No: 4A, Kumsal, Lefkoşa', '(0533) 846 02 77', true, null, 'Ecz. Necla Emin'),
('NERGİS ECZANESİ', 'pharmacy', 'Şht. Mustafa Mehmet Sok. No:3, Göçmenköy, Lefkoşa', '(0392) 225 50 75', true, null, 'Ecz. Nazife Taşker'),
('NERİMAN KARATAÇ ECZANESİ', 'pharmacy', 'Mimar Mehmet Vahip Cad. No: 39/2, Hamitköy, Lefkoşa', '(0392) 225 45 00', true, null, 'Ecz. Neriman Karataç'),
('NİLCAN YAVUZCAN ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Caddesi, Ortaköy, Lefkoşa', '(0392) 223 23 33', true, null, 'Ecz. Nilcan Emine Yavuzcan'),
('OBA 2 ECZANESİ', 'pharmacy', 'Dr. Necmettin Erbakan Cad. No: 49, Küçük Kaymaklı, Lefkoşa', '(0392) 227 13 11', true, null, 'Ecz. Enver Alibaba'),
('OBA ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad. No: 79/D, Ortaköy, Lefkoşa', '(0392) 223 71 01', true, null, 'Ecz. Şerife Alibaba'),
('ORHAN BERKE ECZANESİ', 'pharmacy', 'Öğretmenler Cad., Ortaköy, Lefkoşa', '(0392) 223 31 21', true, null, 'Ecz. Orhan Berke Bilokçuoğlu'),
('ORTAKÖY ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad., Ortaköy, Lefkoşa', '(0392) 330 32 00', true, null, 'Ecz. Didem Can'),
('ÖZÇALIŞKAN ECZANESİ', 'pharmacy', 'Belediye Bulvarı, Yenikent, Lefkoşa', '(0392) 223 11 55', true, null, 'Ecz. İzge Özçalışkan'),
('ÖZERÇAL ECZANESİ', 'pharmacy', 'Raif Denktaş Cad., Göçmenköy, Lefkoşa', '(0392) 223 97 31', true, null, 'Ecz. Öznevir Erçal'),
('ÖZNEM KILINÇKINI ECZANESİ', 'pharmacy', 'Mehmet Akif Cad., Dereboyu, Lefkoşa', '(0392) 227 11 10', true, null, 'Ecz. Öznem Kılınçkını'),
('ÖZYOL ECZANESİ', 'pharmacy', 'Şaziye Hacı Maltızlar Cad. No:2/4, Ortaköy, Lefkoşa', '(0392) 223 21 31', true, null, 'Ecz. Haldun Özyol'),
('PAPATYAM ECZANESİ', 'pharmacy', 'Şht. Gültekin Şengör Sok., Kumsal, Lefkoşa', '(0392) 228 23 30', true, null, 'Ecz. Hande Madi'),
('PERVİN ECZANESİ', 'pharmacy', 'Haydar Aliyev Cad., Küçük Kaymaklı, Lefkoşa', '(0392) 225 28 18', true, null, 'Ecz. Pervin Ayrancıoğlu'),
('RANYA ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Caddesi No: 81/F, Küçük Kaymaklı, Lefkoşa', '(0533) 882 37 37', true, null, 'Ecz. Ranya Eleyan'),
('SABİHA BULDUK ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Cad., Yenişehir, Lefkoşa', '(0392) 228 65 65', true, null, 'Ecz. Sabiha Bulduk'),
('SAFİYE ÇAĞANSEL ECZANESİ', 'pharmacy', 'Şht. İsmail Beyoğlu Cad. No:52A, Küçük Kaymaklı, Lefkoşa', '(0392) 227 76 76', true, null, 'Uzm. Ecz. Safiye Çağansel'),
('ŞERİFE ADEMOĞULLARI ECZANESİ', 'pharmacy', 'Şht. İsmail Dümenci Sok No: 2C, Yenişehir, Lefkoşa', '(0392) 228 17 67', true, null, 'Ecz. Şerife Ademoğulları'),
('SERKAN KERVAN ECZANESİ', 'pharmacy', 'Hürriyet Cad. No: 11/B, Hamitköy, Lefkoşa', '(0392) 225 80 91', true, null, 'Ecz. Serkan Kervan'),
('SERNA ECZANESİ', 'pharmacy', 'Belediye Bulvarı No: 2, Yenikent, Lefkoşa', '(0392) 224 12 10', true, null, 'Ecz. Serna İzel Kaya'),
('SEROL ECZANESİ', 'pharmacy', 'Mustafa Ruso Cad., Küçük Kaymaklı, Lefkoşa', '(0392) 227 20 64', true, null, 'Ecz. Safiye Taydaş'),
('SERPİN ONAY ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Cad. No: 84, Küçük Kaymaklı, Lefkoşa', '(0392) 227 39 24', true, null, 'Ecz. Serpin Onay'),
('SESİL ECZANESİ', 'pharmacy', 'Bolu Sok. Blok 9, Küçük Kaymaklı, Lefkoşa', '(0392) 228 89 63', true, null, 'Ecz. Nurten Özünalp'),
('SEV ECZANESİ', 'pharmacy', 'Kemal Şemiler Cad., Metehan, Lefkoşa', '(0392) 223 44 14', true, null, 'Ecz. Seval Öztürk'),
('SEVAL KAYMAK ECZANESİ', 'pharmacy', 'Prof. Dr. Necmettin Erbakan Cad. No: 41/A, Kızılbaş, Lefkoşa', '(0392) 227 96 19', true, null, 'Ecz. Seval Kaymak'),
('SEVCAN ECZANESİ', 'pharmacy', 'Atatürk Cad., Yenişehir, Lefkoşa', '(0392) 227 60 71', true, null, 'Ecz. Sevcan Güvenir'),
('SEVGİ KARABEKİR ECZANESİ', 'pharmacy', '20 Temmuz Sokak, Yenikent, Gönyeli, Lefkoşa', '(0533) 820 72 84', true, null, 'Ecz. Sevgi Dudu Karabekir'),
('SEVGİ KIRBOĞA ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Cad. No: 33/C, Yenişehir, Lefkoşa', '(0392) 228 05 08', true, null, 'Ecz. Sevgi Kırboğa'),
('SEYRANTEPE ECZANESİ', 'pharmacy', 'Atatürk Cad. 46A, Hamitköy, Lefkoşa', '(0392) 225 57 28', true, null, 'Ecz. Ferdiye Dorak'),
('SEZER ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad. 79/B, Ortaköy, Lefkoşa', '(0392) 223 70 88', true, null, 'Ecz. Meryem Irız'),
('ŞİRİN BOLKAN ECZANESİ', 'pharmacy', 'Atatürk Cad., Hamitköy, Lefkoşa', '(0392) 225 40 20', true, null, 'Ecz. Şirin Bolkan'),
('SONUÇ ECZANESİ', 'pharmacy', 'Atatürk Cad. No: 7/B, Yenişehir, Lefkoşa', '(0392) 227 32 70', true, null, 'Ecz. Ergin Sonuç'),
('SÖZÜÖZ ECZANESİ', 'pharmacy', 'Şht. Mehmet Kemal Sok., Küçük Kaymaklı, Lefkoşa', '(0392) 229 33 00', true, null, 'Ecz. Umut Sözüöz'),
('SÜHEYLA AŞAN ECZANESİ', 'pharmacy', 'Selçuk Avkıran Sok. No: 1, Taşkınköy, Lefkoşa', '(0392) 225 57 30', true, null, 'Ecz. Süheyla Aşan'),
('TÖRENAĞA ECZANESİ', 'pharmacy', 'Gaz. Kemal Aşık Cad. No: 60, Küçük Kaymaklı, Lefkoşa', '(0392) 228 10 08', true, null, 'Ecz. Keziban Şahin Karakaş'),
('TUĞCAN ECZANESİ', 'pharmacy', 'İsmail Beyoğlu Cad., Küçük Kaymaklı, Lefkoşa', '(0392) 229 29 86', true, null, 'Ecz. Tuğcan Burukkan Akçın'),
('TULİS ECZANESİ', 'pharmacy', 'Mimar Mehmet Vahip Cad. No: 46/A, Küçük Kaymaklı, Lefkoşa', '(0539) 137 06 52', true, null, 'Ecz. Melis Emel'),
('TUNA ECZANESİ', 'pharmacy', 'Şht. Ecvet Yusuf Cad., Yenişehir, Lefkoşa', '(0392) 227 78 74', true, null, 'Ecz. Sunay Tuna'),
('TÜRKAN ŞENTİP ECZANESİ', 'pharmacy', 'Belediye Bulvarı No:75/C, Yenikent, Gönyeli, Lefkoşa', '(0392) 223 93 40', true, null, 'Ecz. Türkan Şentip'),
('ÜLKER POZAN ECZANESİ', 'pharmacy', 'Gaz. Hasan Tahsin Cad. 28/2, Ortaköy, Lefkoşa', '(0392) 223 51 80', true, null, 'Ecz. Ülker Pozan'),
('UMUT ÖKSÜZ ECZANESİ', 'pharmacy', 'Şht. Mustafa Ruso Cad. No:17, Küçük Kaymaklı, Lefkoşa', '(0392) 444 86 88', true, null, 'Dr. Ecz. Umut Öksüz'),
('VAİZ ECZANESİ', 'pharmacy', 'Atatürk Caddesi No: 84/C, Yenişehir, Lefkoşa', '(0392) 228 09 90', true, null, 'Ecz. Derviş Doğa Vaiz'),
('YAZMAN ECZANESİ', 'pharmacy', 'Devlet Hastanesi Karşısı, Ortaköy, Lefkoşa', '(0392) 223 21 21', true, null, 'Ecz. Necat Yazman'),
('YELİM ECZANESİ', 'pharmacy', 'Gültekin Şengör Sok., Kumsal, Lefkoşa', '(0392) 228 78 66', true, null, 'Ecz. Tahir Kıbcak'),
('YENİKENT ECZANESİ', 'pharmacy', 'Belediye Bulvarı, Yenikent, Gönyeli, Lefkoşa', '(0392) 223 93 78', true, null, 'Ecz. Düriye Musioğlu'),
('YENİŞEHİR ECZANESİ', 'pharmacy', 'Hüseyin İrfan Sok., Yenişehir, Lefkoşa', '(0392) 227 23 63', true, null, 'Ecz. Ahenk Bilir'),
('YEŞİM ECZANESİ', 'pharmacy', 'Şht. Kemal Ünal Cad., Taşkınköy, Lefkoşa', '(0392) 225 69 18', true, null, 'Ecz. Yeşim Fidanboylu'),
('YONCA HATİPOĞLU ECZANESİ', 'pharmacy', 'Ecvet Yusuf Cad., Kızılbaş, Lefkoşa', '(0392) 228 06 06', true, null, 'Ecz. Yonca Hatipoğlu'),
('YUSUF TANDOĞAN ECZANESİ (LEFKOŞA)', 'pharmacy', 'Mehmet Akif Cad., Dereboyu, Lefkoşa', '(0392) 227 23 50', true, null, 'Ecz. Gizem Karagözlü'),
('ZEHRA ECZANESİ', 'pharmacy', 'Şht. Kemal Ünal Cad. No: 11, Taşkınköy, Lefkoşa', '(0392) 225 59 47', true, null, 'Ecz. Şerife Çağansoy'),
-- GİRNE
('ACARKAN ECZANESİ', 'pharmacy', 'Kordonboyu No: 38, Girne', '(0392) 816 00 08', true, null, 'Ecz. Erol Acarkan'),
('ADAŞEHİR ECZANESİ', 'pharmacy', 'Ecevit Caddesi, Girne', '(0392) 815 01 88', true, null, 'Uzm. Ecz. Fatma Yücelen'),
('AHMET ÇAĞER ECZANESİ', 'pharmacy', 'Ankara Cad. No:50/2A, Alsancak, Girne', '(0392) 821 34 34', true, null, 'Ecz. Ahmet Çağer'),
('ALENBAY ECZANESİ', 'pharmacy', 'Kurtuluş Cad. No: 53/1, Girne', '(0533) 886 12 24', true, null, 'Ecz. Peral Bayramoğulları'),
('ALEV FARUK ECZANESİ', 'pharmacy', 'Şht. Sonay Özdayı Sok. No: 8, Boğazköy, Girne', '(0392) 234 65 96', true, null, 'Ecz. Mustafa Faruk'),
('ARDA ÇELİK ECZANESİ', 'pharmacy', 'Bellapais Yolu, Girne', '(0533) 886 60 85', true, null, 'Ecz. Pervin Çelik'),
('AŞAR ECZANESİ', 'pharmacy', 'Mustafa Çağatay Cad., Girne', '(0392) 815 70 75', true, null, 'Ecz. Aşar Ustaoğlu'),
('AŞAR KARAOĞLANOĞLU ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad. No:3, Girne', '(0392) 822 38 85', true, null, 'Ecz. Vedat Dervişoğlu'),
('ASRIN ÜMİT ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Karaoğlanoğlu, Girne', '(0533) 839 19 60', true, null, 'Ecz. Seyedeh Masha Hojjat Abi'),
('AYDIN LIFE ALSANCAK ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Alsancak, Girne', '(0392) 821 33 61', true, null, 'Ecz. Cankat Ongan'),
('AYDIN LIFE ECZANESİ', 'pharmacy', 'Kurtuluş Cad., Doğanköy, Girne', '(0533) 888 56 66', true, null, 'Ecz. Sezin Türker'),
('AYHAN ACARKAN ECZANESİ', 'pharmacy', 'Dr. Salih Miroğlu Caddesi, Girne', '(0533) 846 02 20', true, null, 'Ecz. Ayhan Halit Acarkan'),
('AYLAND ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Karaoğlanoğlu, Girne', '(0542) 888 29 59', true, null, 'Ecz. Shideh Rozhani'),
('AYŞEN ALTAN ECZANESİ', 'pharmacy', 'Mareşal Fevzi Çakmak Cad. No:121/1, Lapta, Girne', '(0533) 858 52 08', true, null, 'Ecz. Ayşen Altan'),
('BARIŞ ECZANESİ', 'pharmacy', 'Şht. İbrahim Nidai Cad. No:55, Lapta, Girne', '(0392) 821 84 10', true, null, 'Ecz. Ali Öner'),
('BAŞAK ECZANESİ', 'pharmacy', 'Ziya Rızkı Cad. No:31, Girne', '(0392) 815 36 20', true, null, 'Ecz. Erdoğan Başak'),
('BEDEOĞLU ECZANESİ', 'pharmacy', 'Beşparmaklar Cad. No:79, Çatalköy, Girne', '(0392) 824 47 94', true, null, 'Ecz. Evren Bedeoğlu'),
('BOĞAZ ECZANESİ', 'pharmacy', 'Vatan Caddesi, Boğazköy, Girne', '(0533) 847 55 01', true, null, 'Ecz. Bita Pakan'),
('BUĞÇE ECZANESİ', 'pharmacy', 'Zeytinlik yolu, Girne', '(0392) 815 00 32', true, null, 'Ecz. Buğçe Yürüker'),
('CENGİZ SOLMAZ ECZANESİ', 'pharmacy', 'Naci Talat Cad., Girne', '(0533) 844 03 72', true, null, 'Ecz. Cengiz Solmaz'),
('DAMLA ÖNDER ECZANESİ', 'pharmacy', 'Laden Sok. No: 2A, Çamlıbel, Girne', '(0533) 877 80 00', true, null, 'Ecz. Damla Önder'),
('DEFNE ECZANESİ', 'pharmacy', 'Atatürk Cad. No:20, Girne', '(0392) 815 35 16', true, null, 'Ecz. Nilgün Hekimoğlu'),
('DİLARA ÖZHAMİT ECZANESİ', 'pharmacy', 'Mete Adanır Cad., Yukarı Girne, Girne', '(0533) 849 09 74', true, null, 'Ecz. Dilara Özhamit'),
('DÜNYA ECZANESİ', 'pharmacy', 'Salih Miroğlu Cad., Zeytinlik yolu, Girne', '(0392) 815 00 09', true, null, 'Ecz. Canan Çomunoğlu'),
('EDA ATAÇAĞ ECZANESİ', 'pharmacy', 'Dr. Salih Miroğlu Cad. 45/2, Zeytinlik yolu, Girne', '(0548) 881 18 11', true, null, 'Ecz. Eda Ataçağ'),
('EMİNAĞA ECZANESİ', 'pharmacy', 'Ziya Rızkı Cad. No:10, Girne', '(0392) 815 22 48', true, null, 'Ecz. Ahmet Yöney'),
('ENVER POLİLİ ECZANESİ', 'pharmacy', 'Girne', '(0533) 860 63 96', true, null, 'Ecz. Enver Polili'),
('ERDOĞAN ÖZİKİZ ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Girne', '(0548) 870 84 42', true, null, 'Ecz. Ecem Tansoy'),
('ESAT ÇELEBİ ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Cad. No: 47, Dikmen, Girne', '(0392) 237 27 78', true, null, 'Ecz. Esat Çelebi'),
('FATMA SARAÇ ECZANESİ', 'pharmacy', '20 Temmuz Sok. No: 2, Esentepe, Girne', '(0392) 823 63 84', true, null, 'Ecz. Fatma Saraç'),
('GİRNE ECZANESİ', 'pharmacy', 'Işıl Sok., Girne', '(0392) 815 14 47', true, null, 'Ecz. Güzin Çağdan'),
('GÜNAY VARIŞ ECZANESİ', 'pharmacy', 'Uğur Mumcu Cad., Karakum, Girne', '(0392) 815 25 85', true, null, 'Ecz. Günay Arsoy Varış'),
('GÜNDAL ECZANESİ', 'pharmacy', 'Uğur Mumcu Bulvarı, Karakum, Girne', '(0392) 816 05 43', true, null, 'Ecz. Ayşen Günsel Mehmetçik'),
('GÜVEN ECZANESİ', 'pharmacy', 'Salih Miroğlu Cad., Yukarı Girne, Girne', '(0392) 815 24 09', true, null, 'Ecz. Didem Güven'),
('İBRAHİM BARDAK ECZANESİ', 'pharmacy', 'Sakarya Sok., Yukarı Girne, Girne', '(0533) 851 76 08', true, null, 'Ecz. İbrahim Bardak'),
('İLGEN ECZANESİ', 'pharmacy', 'Bedrettin Demirel Cad., Girne', '(0392) 815 81 18', true, null, 'Ecz. İlgen Görgüner'),
('İPEK YÖNEY ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Karaoğlanoğlu, Girne', '(0533) 862 76 56', true, null, 'Ecz. İpek Yöney'),
('KANDİL ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Karaoğlanoğlu, Girne', '(0392) 822 38 42', true, null, 'Ecz. Kadriye Kandil'),
('KARAOĞLANOĞLU ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Caddesi No: 2, Girne', '(0533) 875 39 93', true, null, 'Ecz. Mürüde Musioğlu'),
('KARPUZOĞLU ECZANESİ', 'pharmacy', 'Uğur Mumcu Cad., Karakum, Girne', '(0392) 816 12 30', true, null, 'Ecz. İbrahim Karpuzoğlu'),
('KÜÇÜK ECZANESİ', 'pharmacy', 'Canbulat Sok. No:5/C, Girne', '(0392) 815 36 26', true, null, 'Ecz. Yusuf Küçük'),
('MARYAM ECZANESİ', 'pharmacy', 'Ankara Cad. No: 1, Alsancak, Girne', '(0533) 842 36 37', true, null, 'Ecz. Maryam Mohammed'),
('MEHMET GAZİKÖYLÜ ECZANESİ', 'pharmacy', 'Uğur Mumcu Cad., Karakum, Girne', '(0392) 816 01 23', true, null, 'Ecz. Mehmet Gaziköylü'),
('MEHMET KAMİLOĞLU ECZANESİ', 'pharmacy', 'Mustafa Çağatay Cad. No: 41/C, Girne', '(0533) 887 44 88', true, null, 'Ecz. Mehmet Kamiloğlu'),
('MELİS UZUN ECZANESİ', 'pharmacy', 'Işıl Sokak, Girne', '(0533) 862 11 72', true, null, 'Ecz. Melis Uzun'),
('MELİSA İŞİMTEKİN ECZANESİ', 'pharmacy', 'Uğur Mumcu Caddesi, Ozanköy, Girne', '(0533) 822 94 64', true, null, 'Ecz. Melisa İşimtekin'),
('MELİZ 2 ECZANESİ', 'pharmacy', 'Beyoğlu Sok. No:11, Girne', '(0533) 862 28 82', true, null, 'Ecz. Melis Emek'),
('MUCİZEM ECZANESİ', 'pharmacy', 'Naci Talat Cad. No:26A, Girne', '(0548) 851 11 50', true, null, 'Ecz. Çağın Eseri'),
('NAZIM VARIŞ ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Alsancak, Girne', '(0542) 855 31 14', true, null, 'Ecz. Nazım Varış'),
('NEJLA ERÇAL ECZANESİ', 'pharmacy', 'Üniversite Yolu Sok. No:63/B, Karaoğlanoğlu, Girne', '(0392) 822 32 02', true, null, 'Ecz. Nejla Erçal'),
('NESRİN HATİPOĞLU ECZANESİ', 'pharmacy', 'Nalbant Sokak, Yukarı Girne, Girne', '(0533) 889 73 73', true, null, 'Ecz. Nesrin Hatipoğlu'),
('NURÇAĞ ECZANESİ', 'pharmacy', 'Semih Sancar Caddesi, Yukarı Girne, Girne', '(0533) 886 70 40', true, null, 'Ecz. Nurçağ Madi'),
('ÖMRÜM AKI ECZANESİ', 'pharmacy', 'İstiklal Cad. No:1, Esentepe, Girne', '(0533) 882 32 39', true, null, 'Ecz. Ömrüm Akı'),
('ÖMRÜM ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad. No:256, Girne', '(0392) 822 22 87', true, null, 'Ecz. Sergül Akı'),
('ÖNAL AKTOLGA ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad. No:33, Girne', '(0392) 822 41 42', true, null, 'Ecz. Önal Aktolga'),
('ORÇUN ÖZKASAP ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Caddesi, Karaoğlanoğlu, Girne', '(0533) 870 21 22', true, null, 'Ecz. Orçun Özkasap'),
('ÖZENİR ECZANESİ', 'pharmacy', 'Mareşal Fevzi Çakmak Cad., Lapta, Girne', '(0542) 876 06 60', true, null, 'Ecz. Emine Türk'),
('ÖZGE ÖZÇINAR ECZANESİ', 'pharmacy', 'Mete Adanır Cad., Girne', '(0392) 815 90 90', true, null, 'Dr. Ecz. Özge Özçınar'),
('PINAR KEKLİK ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad. 198/A, Alsancak, Girne', '(0533) 857 54 94', true, null, 'Ecz. Pınar Keklik'),
('POSTACIOĞLU ECZANESİ', 'pharmacy', 'Mustafa Çağatay Cad., Girne', '(0392) 815 11 00', true, null, 'Ecz. Dilek Postacıoğlu'),
('RIZKI 2 ECZANESİ', 'pharmacy', 'Çatalköy, Girne', '(0392) 824 56 06', true, null, 'Ecz. Mediha Keleşoğlu'),
('RIZKI ECZANESİ', 'pharmacy', 'Beşparmaklar Cad. No:155/2, Çatalköy, Girne', '(0392) 815 34 96', true, null, 'Ecz. Zehra Keleşoğlu'),
('SALİM KARABEKİR ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Alsancak, Girne', '(0533) 845 98 36', true, null, 'Ecz. Salim Karabekir'),
('SELİN ESER ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Cad., Girne', '(0392) 815 06 66', true, null, 'Ecz. Selin Eser'),
('SERTAÇ ECZANESİ', 'pharmacy', 'Osman Örek Caddesi, Girne', '(0392) 815 90 67', true, null, 'Ecz. Kıvanç İlter'),
('SETENAY BENGİSU ECZANESİ', 'pharmacy', 'Doğanköy, Girne', '(0392) 816 00 82', true, null, 'Ecz. Setenay Bengisu'),
('SEVİN ÇAĞAY ECZANESİ', 'pharmacy', 'Ecevit Cad. No: 67/B, Girne', '(0392) 815 20 25', true, null, 'Ecz. Sevin Çağay'),
('SHİMA ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Karaoğlanoğlu, Girne', '(0548) 822 02 72', true, null, 'Ecz. Shima Abdihagh Gezer'),
('ŞİFALI ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Alsancak, Girne', '(0533) 846 33 30', true, null, 'Ecz. Ayşe Türk'),
('SOYERLER 1 ECZANESİ', 'pharmacy', 'Naci Talat Caddesi, Girne', '(0533) 833 07 17', true, null, 'Ecz. Selçuk Soyer'),
('SOYERLER ECZANESİ', 'pharmacy', 'Karaoğlanoğlu Cad., Alsancak, Girne', '(0533) 830 07 17', true, null, 'Ecz. Göksel Soyer'),
('ŞULE YILDIZDOĞAN ECZANESİ', 'pharmacy', 'Salih Miroğlu Cad., Girne', '(0392) 816 12 13', true, null, 'Ecz. Şule Yıldızdoğan'),
('TÖREN 2 ECZANESİ', 'pharmacy', 'Vakıflar Çarşısı A Blok No:1, Girne', '(0392) 815 17 90', true, null, 'Ecz. Ahmet Eminağa'),
('TÖREN ECZANESİ', 'pharmacy', 'Ziya Rızkı Cad., Girne', '(0392) 815 89 79', true, null, 'Ecz. Ayça Eminağa İpekdal'),
('TÖRENSEL ECZANESİ', 'pharmacy', 'Beşparmaklar Cad., Çatalköy, Girne', '(0392) 824 57 13', true, null, 'Ecz. Doğan Başak'),
('TURGAY PARALI ECZANESİ', 'pharmacy', 'Semih Sancar Cad., Girne', '(0533) 837 61 26', true, null, 'Ecz. Turgay Paralı'),
('VURAL ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Cad. No:35/2, Dikmen, Girne', '(0392) 237 30 19', true, null, 'Ecz. Kemal Vural'),
('YUSUF TANDOĞAN ECZANESİ (GİRNE)', 'pharmacy', 'Beşparmaklar Cad., Çatalköy, Girne', '(0548) 865 34 34', true, null, 'Ecz. Asrem Karagözlü'),
('ZEHRA KELEBEK ECZANESİ', 'pharmacy', 'Mareşal Fevzi Çakmak Cad., Lapta, Girne', '(0392) 821 38 88', true, null, 'Ecz. Zehra Kelebek'),
('ZİYA SENCER ECZANESİ', 'pharmacy', 'Mete Adanır Cad., Girne', '(0533) 826 51 91', true, null, 'Ecz. Ziya Sencer'),
-- GAZİMAĞUSA
('ADA ECZANESİ', 'pharmacy', 'Salamis yolu, Gazimağusa', '(0392) 365 31 30', true, null, 'Ecz. Eylem Körceğez'),
('ARAS ÖNCÜ ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı No: 46, Çanakkale, Gazimağusa', '(0533) 861 70 98', true, null, 'Ecz. Aras Öncü'),
('ARKAN ADIŞANLI ECZANESİ', 'pharmacy', 'Yalı Mah., Tatlısu, Gazimağusa', '(0548) 853 15 53', true, null, 'Ecz. Arkan Adışanlı'),
('ASLI EREN ECZANESİ', 'pharmacy', 'Ziya Gökalp Caddesi No: 41, Maraş, Gazimağusa', '(0392) 366 47 47', true, null, 'Ecz. Aslı Eren'),
('ASYA TEKBIYIK ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı, Gazimağusa', '(0392) 365 13 38', true, null, 'Ecz. Asya Tekbıyık'),
('AYBENK ECZANESİ', 'pharmacy', 'Gülseren yolu, Karakol Bölgesi, Gazimağusa', '(0533) 870 37 88', true, null, 'Ecz. Abdullah Aybenk'),
('AYŞE EMİROĞLULARI ECZANESİ', 'pharmacy', 'Yenikent Bulvarı, Yeniboğaziçi, Gazimağusa', '(0533) 841 98 13', true, null, 'Ecz. Hasibe Emiroğluları'),
('AYŞE ÖZBEYCAN ECZANESİ', 'pharmacy', 'Topçu Bulvarı, Gazimağusa', '(0392) 365 68 38', true, null, 'Ecz. Ayşe Özbeycan'),
('AYŞEM ÇİL ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Larnaka Yolu, Gazimağusa', '(0392) 366 20 26', true, null, 'Ecz. Ayşem Çil'),
('BAHAR ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı No: 45, Gazimağusa', '(0392) 365 51 26', true, null, 'Ecz. Bahar Kilim'),
('BARIŞER ECZANESİ', 'pharmacy', 'Gazimağusa', '(0392) 365 60 40', true, null, 'Ecz. Ali Barışer'),
('BİLGESU ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Caddesi, Yeniboğaziçi, Gazimağusa', '(0533) 888 82 90', true, null, 'Ecz. Bilgesu Kaçar'),
('BUĞÇE BAYRAM ECZANESİ', 'pharmacy', 'Uluçam Sokak, Gazimağusa', '(0392) 365 25 25', true, null, 'Ecz. Buğçe Bayram'),
('BURCU GÖKALP ECZANESİ', 'pharmacy', 'Kaliland Bölgesi, Gazimağusa', '(0392) 365 69 39', true, null, 'Ecz. Burcu Gökalp'),
('ÇAĞKAN AKSOY ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Larnaka Yolu, Gazimağusa', '(0392) 366 95 55', true, null, 'Ecz. Çağkan Aksoy'),
('ÇAĞLAN ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı No:34, Gazimağusa', '(0392) 366 64 47', true, null, 'Ecz. Behiye Zorlu'),
('CAN İLKTAÇ ECZANESİ', 'pharmacy', 'Aydan Karahan Cad. No: 64, Mutlukaya, Gazimağusa', '(0548) 839 83 39', true, null, 'Ecz. Parandis İlktaç'),
('CEREN ECZANESİ', 'pharmacy', 'Larnaka Yolu, Gazimağusa', '(0392) 366 33 74', true, null, 'Ecz. Aliye Kürüm'),
('ÇİSE SEZEREL ECZANESİ', 'pharmacy', 'Ziya Gökalp Cad. No:34, Gazimağusa', '(0392) 366 39 15', true, null, 'Ecz. Çise Sezerel'),
('ÇİSEM ECZANESİ', 'pharmacy', 'Halil Hamza Yolu, Kaliland Bölgesi, Gazimağusa', '(0392) 365 40 04', true, null, 'Ecz. Çisem Tacel'),
('DEMET ECZANESİ', 'pharmacy', 'Gazimağusa', '(0392) 366 33 50', true, null, 'Ecz. Demet İlerici'),
('ECE ECZANESİ', 'pharmacy', 'Mustafa Kemal Bulvarı, Gazimağusa', '(0392) 366 38 46', true, null, 'Ecz. Ece Gülaç'),
('EMİR ECZANESİ', 'pharmacy', 'Gülseren Yolu, Karakol Bölgesi, Gazimağusa', '(0392) 365 54 54', true, null, 'Ecz. Emir Akşahoğlu'),
('EREL ECZANESİ', 'pharmacy', 'Salamis yolu, Gazimağusa', '(0392) 864 93 85', true, null, 'Ecz. Nazife Sağlamer'),
('ERGİN ECZANESİ', 'pharmacy', 'Gazimağusa', '(0392) 365 47 35', true, null, 'Ecz. Ergin İlktaç'),
('ERTUĞ EMİN ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı, Sakarya, Gazimağusa', '(0392) 365 60 60', true, null, 'Ecz. Ertuğ Emin'),
('EYLÜL DALKILINÇ ECZANESİ', 'pharmacy', 'Şht. İbrahim Hasan Sokak, Çanakkale, Gazimağusa', '(0533) 869 67 94', true, null, 'Ecz. Eylül Dalkılınç'),
('FAYDALI ECZANESİ', 'pharmacy', 'Devlet Hastanesi Yolu, Gazimağusa', '(0392) 365 69 22', true, null, 'Ecz. Olcay Faydalı'),
('FUNDA ERSÖZLÜ ECZANESİ', 'pharmacy', 'Anafartalar Caddesi, Karakol, Gazimağusa', '(0542) 888 81 00', true, null, 'Ecz. Funda Ersözlü'),
('GİZEM KARAHASAN ECZANESİ', 'pharmacy', 'Yeni Hastane yolu, Tuzla, Gazimağusa', '(0533) 880 84 94', true, null, 'Ecz. Gizem Karahasan'),
('GİZEMGÜL ECZANESİ', 'pharmacy', 'Yeniboğaziçi, Gazimağusa', '(0392) 378 98 98', true, null, 'Ecz. Gizemgül Beşergil'),
('GÖKCEN İLKTAÇ ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı No: 145, Gazimağusa', '(0392) 365 68 20', true, null, 'Ecz. Mehmet Tut'),
('GÜLFİDAN ECZANESİ', 'pharmacy', 'İstiklal Cad. No:195/2, Yeniboğaziçi, Gazimağusa', '(0392) 378 94 14', true, null, 'Ecz. Gülfidan Köseoğlu'),
('GÜZER ECZANESİ', 'pharmacy', 'Çanakkale, Gazimağusa', '(0533) 874 03 74', true, null, 'Ecz. Bahar Güzer'),
('HACER BALIKÇI ECZANESİ', 'pharmacy', 'Mustafa Kemal Bulvarı, Gazimağusa', '(0392) 365 55 18', true, null, 'Ecz. Hacer Balıkçı'),
('HAKAN ECZANESİ', 'pharmacy', 'Kocatepe Sok. No:1, Gazimağusa', '(0392) 366 27 13', true, null, 'Ecz. Nurten Göksan'),
('HALİL HAMZALAR ECZANESİ', 'pharmacy', 'Halil Hamza Yolu, Kaliland Bölgesi, Gazimağusa', '(0392) 365 55 94', true, null, 'Ecz. Halil Hamzalar'),
('HALK ECZANESİ', 'pharmacy', 'Namık Kemal Meydanı, Suriçi, Gazimağusa', '(0392) 366 53 33', true, null, 'Ecz. Ayten Bayram'),
('HALKIN ECZANESİ', 'pharmacy', 'Ulucam Yolu, Sakarya, Gazimağusa', '(0392) 365 01 12', true, null, 'Ecz. Esra Halkın'),
('HANDE BESMEL ECZANESİ', 'pharmacy', 'Gülseren Yolu, Karakol Bölgesi, Gazimağusa', '(0392) 365 34 50', true, null, 'Ecz. Hande Besmel'),
('HİÇKORKMAZ ECZANESİ', 'pharmacy', 'Kaliland, Gazimağusa', '(0533) 832 24 03', true, null, 'Ecz. Laika Hiçkorkmaz'),
('İÇTEN ECZANESİ', 'pharmacy', 'Eşref Bitlis Cad., Gazimağusa', '(0392) 365 22 00', true, null, 'Ecz. Barış Kıvançlı'),
('İNEM MİMAR ECZANESİ', 'pharmacy', 'Hasan Barbaçolli Sok., Sakarya, Gazimağusa', '(0548) 842 27 95', true, null, 'Ecz. İnem Mimar'),
('KAĞAN KANDEMİR ECZANESİ', 'pharmacy', 'Samanyolu Sokak, Kaliland, Gazimağusa', '(0533) 881 66 26', true, null, 'Ecz. Kağan Kandemir'),
('KARAKOL ECZANESİ', 'pharmacy', 'Gülseren yolu, Karakol, Gazimağusa', '(0392) 365 65 19', true, null, 'Ecz. Sevtap Zeki'),
('KUNTER GÜVEN ECZANESİ', 'pharmacy', 'Karakız Sokak No: 2, Gazimağusa', '(0392) 366 19 09', true, null, 'Ecz. Ahmet Kunter'),
('LARNAKA YOLU ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Çanakkale, Gazimağusa', '(0533) 860 59 65', true, null, 'Ecz. Sibel Kösedağ'),
('LOTUSVİTA ECZANESİ', 'pharmacy', 'Dr. Küçük Cad., Yeniboğaziçi, Gazimağusa', '(0533) 861 27 28', true, null, 'Ecz. Mohamad Nour Abulkarım'),
('MEHMET ARTER ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Larnaka Yolu, Gazimağusa', '(0392) 366 00 02', true, null, 'Ecz. Mehmet Arter'),
('MEHMETALİ BEYAZ ECZANESİ', 'pharmacy', 'Eşref Bitlis Cad., Gazimağusa', '(0392) 365 06 50', true, null, 'Ecz. Mehmetali Beyaz'),
('MELİKE BARBAROS ECZANESİ', 'pharmacy', 'Şht. İbrahim Hasan Cad., Gazimağusa', '(0392) 365 42 40', true, null, 'Ecz. Melike Barbaros'),
('MELİKE DEMİRSÖZ ECZANESİ', 'pharmacy', 'Gençlik Sokak No: 40, Dumlupınar, Gazimağusa', '(0392) 366 50 71', true, null, 'Ecz. Melike Demirsöz'),
('MEVA ECZANESİ', 'pharmacy', 'Ordu Sok. No:15/A, Çanakkale, Gazimağusa', '(0548) 837 23 23', true, null, 'Ecz. Meva Arter'),
('NADİRE GÖKALP ECZANESİ', 'pharmacy', 'Salamis Yolu, Gazimağusa', '(0539) 110 01 12', true, null, 'Ecz. Nadire Gökalp'),
('NASİM ECZANESİ', 'pharmacy', 'Salamis Yolu, Gazimağusa', '(0392) 365 03 40', true, null, 'Ecz. Faysal Zeki'),
('NİLHAN SOYSAL ECZANESİ', 'pharmacy', 'Silahlı Kuvvetler Cad., Gazimağusa', '(0392) 366 03 53', true, null, 'Ecz. Nilhan Soysal'),
('ODUNCUOĞLU ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Gazimağusa', '(0392) 366 50 51', true, null, 'Ecz. Başak Sabiha Oduncuoğlu'),
('ÖREN ECZANESİ', 'pharmacy', 'Cengizhan yolu No: 91, Maraş, Gazimağusa', '(0392) 366 34 57', true, null, 'Ecz. Cem Ören'),
('OSMANKAN ECZANESİ', 'pharmacy', 'Hüseyin Durmuş Sok., Larnaka Yolu, Gazimağusa', '(0392) 366 92 97', true, null, 'Ecz. Emre Osmankan'),
('ÖZAY ECZANESİ', 'pharmacy', 'Altay Sok., Baykal, Gazimağusa', '(0392) 366 48 36', true, null, 'Ecz. Özay Atamözlü'),
('ÖZGE KALE ECZANESİ', 'pharmacy', 'Şht. İbrahim Hasan Sok., Gazimağusa', '(0392) 366 88 66', true, null, 'Ecz. Özge Kale'),
('ÖZNERGİS ECZANESİ', 'pharmacy', 'Salamis Yolu, Gazimağusa', '(0392) 365 24 92', true, null, 'Ecz. Necla Öznergis'),
('PETEK ECZANESİ', 'pharmacy', 'Zafer Anıtı Ticaret Merkezi, Gazimağusa', '(0392) 366 29 28', true, null, 'Ecz. Semra Gani'),
('PHARMATOWN ECZANESİ', 'pharmacy', 'İsmet İnönü Sok. No:12, Yeniboğaziçi, Gazimağusa', '(0392) 378 95 06', true, null, 'Ecz. Himmet Soner'),
('RANA YONTAR ECZANESİ', 'pharmacy', 'Şht. İbrahim Hasan Sok., Çanakkale, Gazimağusa', '(0392) 366 19 19', true, null, 'Ecz. Rana Yontar'),
('REVİTA ECZANESİ', 'pharmacy', 'Hasan Güvenir Caddesi No: 2, Tuzla, Gazimağusa', '(0533) 869 03 79', true, null, 'Ecz. Ali Öztürk'),
('REZAN ECZANESİ', 'pharmacy', 'Salamis Yolu, Gazimağusa', '(0392) 365 69 11', true, null, 'Ecz. Rezan Mevlit'),
('SAKARYA ECZANESİ', 'pharmacy', 'Narlı Sok., Sakarya, Gazimağusa', '(0392) 365 29 89', true, null, 'Ecz. Tijen Coşar'),
('SEMAHAT ATAYOL ECZANESİ', 'pharmacy', 'Üç Çakırlar Cad., Maraş, Gazimağusa', '(0392) 366 91 93', true, null, 'Ecz. Semahat Atayol'),
('SERHAT BAYBORA ECZANESİ', 'pharmacy', 'Selvi Sokak, Tuzla, Gazimağusa', '(0548) 835 00 54', true, null, 'Ecz. Serhat Baybora'),
('SÜAY SEVİNÇ ECZANESİ', 'pharmacy', 'Salamis Yolu No: 168A, Gazimağusa', '(0392) 365 42 80', true, null, 'Ecz. Süay Sevinç'),
('SÜMER ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı 182/A, Gazimağusa', '(0392) 365 49 69', true, null, 'Ecz. Banu Tuzlalı'),
('TANYA SALİMER ECZANESİ', 'pharmacy', '15 Ağustos Bulvarı, Baykal, Gazimağusa', '(0392) 366 99 88', true, null, 'Ecz. Tanya Salimer'),
('TURGUT KORHAN ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı, Dumlupınar, Gazimağusa', '(0548) 878 77 57', true, null, 'Ecz. Turgut Korhan'),
('ULUÇAY ECZANESİ', 'pharmacy', 'Gazimağusa', '(0392) 365 24 24', true, null, 'Ecz. Tezer Uluçay'),
('UMUT ECZANESİ', 'pharmacy', 'Salamis yolu, Gazimağusa', '(0392) 366 23 69', true, null, 'Ecz. Ayşe Ayman'),
('UZAY ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı, Gazimağusa', '(0392) 365 56 56', true, null, 'Ecz. Çisem İçten'),
('VELİ ATEŞ ECZANESİ', 'pharmacy', 'Salamis Yolu, Gazimağusa', '(0392) 365 04 19', true, null, 'Ecz. Sema Ateş'),
('VELİ NURLUÖZ ECZANESİ', 'pharmacy', 'Sakarya, Gazimağusa', '(0392) 365 36 31', true, null, 'Ecz. Veli Nurluöz'),
('VEZİROĞLU ECZANESİ', 'pharmacy', 'Anafartalar Cad., Karakol, Gazimağusa', '(0392) 365 69 77', true, null, 'Ecz. Fatma Veziroğlu'),
('ZERİN VOLKAN ECZANESİ', 'pharmacy', 'Gazimağusa', '(0392) 365 59 59', true, null, 'Ecz. Zerin Volkan'),
('ZEYNEP ECZANESİ', 'pharmacy', 'İsmet İnönü Bulvarı No: 7, Gazimağusa', '(0392) 365 18 47', true, null, 'Ecz. Zeynep İlktaç'),
-- GÜZELYURT
('AKÇAY ECZANESİ', 'pharmacy', 'Naci Talat Caddesi No: 1, Akçay, Güzelyurt', '(0392) 725 84 77', true, null, 'Ecz. Dilek Kara'),
('AŞAR ECZANESİ (GÜZELYURT)', 'pharmacy', 'Ecevit Cad. 18/B, Güzelyurt', '(0392) 714 21 93', true, null, 'Dr. Ecz. Özgür Karataşlı'),
('AYCAN ECZANESİ', 'pharmacy', 'Ecevit Cad. 4J, Güzelyurt', '(0392) 714 23 16', true, null, 'Ecz. Aycan Eşrefoğlu'),
('CAMCIOĞLU ECZANESİ', 'pharmacy', 'Şht. Mümür Dilaver Sok No:24C, Güzelyurt', '(0392) 714 24 57', true, null, 'Ecz. Perin Camcıoğlu'),
('DOĞUŞ TÜRKBAYOĞLU ECZANESİ', 'pharmacy', 'Şht. Hasan Cafer Sk., Güzelyurt', '(0533) 836 43 58', true, null, 'Ecz. Doğuş Türkbayoğlu'),
('EMİNE ŞENTÜRK ECZANESİ', 'pharmacy', 'Büyük Ada Sok No: 22, Güzelyurt', '(0533) 851 58 21', true, null, 'Ecz. Emine Şentürk'),
('ERİN ECZANESİ', 'pharmacy', 'Kutlu Adalı Bulvarı No:41, Güzelyurt', '(0392) 714 70 52', true, null, 'Ecz. Erin Egesoy Kamer'),
('GİLANLI ECZANESİ', 'pharmacy', 'Ecevit Cad. No: 120B, Güzelyurt', '(0533) 868 47 90', true, null, 'Ecz. Ayten Gilanlıoğulları'),
('GÜLSEN ECZANESİ', 'pharmacy', 'Piyale Paşa Mahallesi, Güzelyurt', '(0392) 714 11 90', true, null, 'Ecz. Gülsen Ünlüyol'),
('İLAYDA GÜLKAN ECZANESİ', 'pharmacy', 'Şht. Celal Bekiroğlu Sokak, Aşağı Bostancı, Güzelyurt', '(0392) 714 60 22', true, null, 'Ecz. İlayda Gülkan'),
('İLKİN SADRAZAM ECZANESİ', 'pharmacy', 'Binatlı Sok. No:6A/B, Güzelyurt', '(0392) 714 12 22', true, null, 'Ecz. İlkin Sadrazam'),
('İNCİ ECZANESİ', 'pharmacy', 'Kutlu Adalı Bulvarı No: 1K, Güzelyurt', '(0392) 714 32 52', true, null, 'Ecz. İnci Dizgin Nazım'),
('JENNET BAYLİYEVA ECZANESİ', 'pharmacy', 'Sarmaşık Sok. No: 3A, Kalkanlı, Güzelyurt', '(0542) 875 54 33', true, null, 'Ecz. Jennet Bayliyeva'),
('MERVE GÜMÜŞOK ECZANESİ', 'pharmacy', 'İzzet Kombos Bulvarı No:148, Güzelyurt', '(0392) 714 44 48', true, null, 'Ecz. Merve Gümüşok'),
('NİLGÜN ECZANESİ', 'pharmacy', 'Ecevit Cad. 25, Güzelyurt', '(0392) 714 38 47', true, null, 'Ecz. Nilgün Faruk'),
('PEMBE SADIKOĞLU ECZANESİ', 'pharmacy', 'Kutlu Adalı Bulvarı, Güzelyurt', '(0533) 840 01 99', true, null, 'Ecz. Pembe Sadıkoğlu'),
('RESMİYE ESE ECZANESİ', 'pharmacy', 'Ecevit Cad. No:75/1, Güzelyurt', '(0392) 714 45 18', true, null, 'Ecz. Resmiye Ese'),
('SEDEF SONAT ECZANESİ', 'pharmacy', 'Şht. Hasan Cafer Sokak No: 12, Güzelyurt', '(0392) 714 18 94', true, null, 'Ecz. Sedef Sonat'),
('SERCAN AVCI ECZANESİ', 'pharmacy', 'Şht. Raşit Osman Sok. No:2/E, Güzelyurt', '(0392) 714 48 94', true, null, 'Ecz. Sercan Avci'),
('SEVİL ECZANESİ', 'pharmacy', 'Ecevit Cad. 55, Güzelyurt', '(0392) 714 35 91', true, null, 'Ecz. Mustafa Zeybekoğulları'),
('ŞİFA SİPERCİ ECZANESİ', 'pharmacy', 'Büyük Ada Sokak No: 12, Güzelyurt', '(0392) 714 37 77', true, null, 'Ecz. Şifa Siperci'),
('SÜREYYA ÖZCOŞKUN ECZANESİ', 'pharmacy', 'Şht. Mehmet Sokollu Sok., Güzelyurt', '(0392) 714 20 00', true, null, 'Ecz. Süreyya Özcoşkun'),
('UYUMSAL ECZANESİ', 'pharmacy', 'Kutlu Adalı Bulvarı 3A, Güzelyurt', '(0392) 714 30 05', true, null, 'Ecz. Ayşe Pilancı'),
-- LEFKE
('ALTINCI ECZANESİ', 'pharmacy', 'Şht. Nejdet Levent Sok. No: 4A, Denizli, Lefke', '(0392) 727 85 00', true, null, 'Ecz. Çağın Altıncı'),
('AYŞE ALTINTUĞ ECZANESİ', 'pharmacy', 'Şht. Fuat Yakup Sok. No:7, Denizli, Lefke', '(0542) 872 69 74', true, null, 'Ecz. Ayşe Çizer'),
('DERVİŞ KUTRET ECZANESİ', 'pharmacy', 'Dr. İzzet Salih Suphi Meydanı No:5, Lefke', '(0533) 882 94 56', true, null, 'Ecz. Derviş Kutret'),
('DİLAN PUL ECZANESİ', 'pharmacy', 'Ecevit Cad., Yeşilyurt, Lefke', '(0392) 723 73 33', true, null, 'Ecz. Dilan Pul'),
('HATİCE SOYER ECZANESİ', 'pharmacy', 'Cengizköy, Lefke', '(0548) 865 52 91', true, null, 'Ecz. Hatice Soyer'),
('İLKSEN ECZANESİ', 'pharmacy', 'Belediye Dükkanları No:18, Gemikonağı, Lefke', '(0392) 727 82 40', true, null, 'Ecz. İlksen Ahçıhoca'),
('OSMAN ULUŞAN ECZANESİ', 'pharmacy', 'Yeni Elye Sokak No:196, Doğancı, Lefke', '(0533) 860 65 43', true, null, 'Ecz. Osman Uluşan'),
('SIDIKA UMAR ECZANESİ', 'pharmacy', 'Menekşe Sok. No: 2/B, Gaziveren, Lefke', '(0392) 723 79 97', true, null, 'Ecz. Sıdıka Umar'),
('ŞİFA BILDIR ECZANESİ', 'pharmacy', 'Fuat Yakup Sok. No:1/1, Denizli, Lefke', '(0533) 841 95 78', true, null, 'Ecz. Şifa Bıldır'),
('ULUS ECZANESİ', 'pharmacy', 'Ecevit Cad. No:11, Lefke', '(0392) 727 76 49', true, null, 'Ecz. Ulus Sabit'),
-- ÜST MESARYA
('ESER AVCI ECZANESİ', 'pharmacy', 'Özgürlük Cad. No: 11/B, Cihangir, Üst Mesarya', '(0533) 855 06 04', true, null, 'Ecz. Eser Avcı'),
('GÖNÜL GÜRDAĞ ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Cad. No 30, Demirhan, Üst Mesarya', '(0539) 105 48 88', true, null, 'Ecz. Gönül Gürdağ'),
('GÜLTEN VELİ ECZANESİ', 'pharmacy', 'Cumhuriyet Cad. 79/B, Cihangir, Üst Mesarya', '(0392) 232 35 00', true, null, 'Ecz. Gülten Veli'),
('KEZBAN DOYGUNEL ECZANESİ', 'pharmacy', 'Atatürk Cad. No: 2/A, Geçitkale, Üst Mesarya', '(0392) 373 33 60', true, null, 'Ecz. Simge Soğancı'),
('MELİZ ECZANESİ', 'pharmacy', 'Lefkoşa-Mağusa Anayolu, Demirhan, Üst Mesarya', '(0533) 872 42 62', true, null, 'Ecz. Bilgen Şimşek'),
('ŞEHERLİOĞLU ECZANESİ', 'pharmacy', 'Zafer Caddesi No:30, Haspolat, Üst Mesarya', '(0392) 233 55 33', true, null, 'Dr. Ecz. Barış İzzet'),
('SERDARLI ECZANESİ', 'pharmacy', 'Serdarlı, Üst Mesarya', '(0392) 376 70 06', true, null, 'Ecz. Özlem Toydemir'),
('TUFAN ECZANESİ', 'pharmacy', 'Çelik İş Merkezi, Demirhan, Üst Mesarya', '(0392) 232 48 15', true, null, 'Ecz. İsmet Tufan'),
('YAPRAK POLAT ECZANESİ', 'pharmacy', 'Zafer Caddesi No: 34, Haspolat, Üst Mesarya', '(0533) 847 68 65', true, null, 'Ecz. Yaprak Polat'),
('YÜKSEL ECZANESİ', 'pharmacy', 'Minareliköy, Değirmenlik, Üst Mesarya', '(0542) 875 21 12', true, null, 'Ecz. Yüksel Esma Arslaner'),
-- ALT MESARYA
('BUĞRA ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Cad., Akdoğan, Alt Mesarya', '(0392) 377 88 25', true, null, 'Ecz. Buğra Cömert'),
('DOĞUŞ ACARÖZ ECZANESİ', 'pharmacy', 'Atatürk Cad. No:1, İnönü, Alt Mesarya', '(0548) 871 72 59', true, null, 'Ecz. Doğuş Acaröz'),
('DÖRTYOL ECZANESİ', 'pharmacy', 'Recep Tayip Erdoğan Cad. No:C-1, Dörtyol, Alt Mesarya', '(0542) 851 64 34', true, null, 'Ecz. Ediz Toydemir'),
('GÜNER BİNBOĞA ECZANESİ', 'pharmacy', 'Atatürk Cad. No: 4, Paşaköy, Alt Mesarya', '(0392) 236 91 00', true, null, 'Ecz. Güner Binboğa'),
('GÜRSOY ECZANESİ', 'pharmacy', 'Akdoğan, Alt Mesarya', '(0392) 377 90 69', true, null, 'Ecz. Ayberk Gürsoy'),
('HERA AKESEN ECZANESİ', 'pharmacy', 'Şht. Hüseyin Kafa Cad. No:2, Beyarmudu, Alt Mesarya', '(0533) 822 29 99', true, null, 'Ecz. Ceren Celal'),
('HOCANIN ECZANESİ', 'pharmacy', 'Belediye Dük No: 1, Vadili, Alt Mesarya', '(0392) 397 82 22', true, null, 'Ecz. Türkay Hocanın'),
('KINAY ECZANESİ', 'pharmacy', 'Mersinli Sok. No: C/4, Türkmenköy, Alt Mesarya', '(0392) 377 70 70', true, null, 'Ecz. Gökcen Kınay'),
('KUDRET ECZANESİ', 'pharmacy', 'Vatan Cad. No:95, Vadili, Alt Mesarya', '(0392) 397 70 00', true, null, 'Ecz. Kardelen Varanoğluları'),
('MEHMET HOCA ECZANESİ', 'pharmacy', 'Özgürlük Cad., Türkmenköy, Alt Mesarya', '(0533) 873 30 98', true, null, 'Ecz. Ali Hoca'),
('PHARGAMOS ECZANESİ', 'pharmacy', 'Şht. Hüseyin Kafa Cad. No: 2, Beyarmudu, Alt Mesarya', '(0548) 851 52 00', true, null, 'Ecz. Turan Ceyda'),
('SERVET GÖKŞİN ECZANESİ', 'pharmacy', 'Atatürk Caddesi No: 72, Dilekkaya, Alt Mesarya', '(0533) 830 84 01', true, null, 'Ecz. Servet Gökşin'),
('VADİLİ ECZANESİ', 'pharmacy', 'Vatan Cad. No: 95, Vadili, Alt Mesarya', '(0533) 882 40 11', true, null, 'Ecz. Melek Tilki'),
-- İSKELE
('AVİCENNA ECZANESİ', 'pharmacy', 'İskele Boğaz anayolu, İskele', '(0542) 855 00 15', true, null, 'Ecz. Omar A. Hwaileh'),
('BUSE ULUÇAY ECZANESİ', 'pharmacy', 'Şehit İlker Karter Caddesi No: 30/A, Yeni İskele', '(0533) 828 22 44', true, null, 'Ecz. Buse Uluçay'),
('ERDEM SURURİ ECZANESİ', 'pharmacy', 'Şht. Günay Bey Caddesi No: 13/C, İskele', '(0548) 844 12 78', true, null, 'Ecz. Erdem Sururi Ayhan'),
('ERSU ADAN ECZANESİ', 'pharmacy', 'Dr. Fazıl Küçük Bulvarı, Ötüken, İskele', '(0392) 378 88 87', true, null, 'Ecz. Ersu Adan'),
('GÖKBERK ALP YAKAR ECZANESİ', 'pharmacy', 'Mekanizi Cad., İskele', '(0539) 109 95 77', true, null, 'Ecz. Gökberk Alp Yakar'),
('İSKELE ECZANESİ', 'pharmacy', 'Şht. İlker Karter Cad., İskele', '(0539) 117 12 35', true, null, 'Ecz. Arzu Baysal'),
('MEHMET İLBAN ECZANESİ', 'pharmacy', 'Atatürk Cad., Boğaz, İskele', '(0533) 834 82 51', true, null, 'Ecz. Mehmet İlban'),
('MEVLÜT KAÇMAZ ECZANESİ', 'pharmacy', 'Makenzi Cad., Cevizli, İskele', '(0548) 860 55 54', true, null, 'Ecz. Mevlüt Kaçmaz'),
('NALAN ECZANESİ', 'pharmacy', 'Kordonboyu Cad. No:35/B, Bahçeler, İskele', '(0392) 371 40 06', true, null, 'Ecz. Nalan İzzigil'),
('ÖZBİRTAN ECZANESİ', 'pharmacy', 'Dt. Temel Zeki Cad., İskele', '(0392) 371 22 24', true, null, 'Ecz. Pembe Özbirtan'),
('PERTEV ZEKİ ECZANESİ', 'pharmacy', 'Larnaka Yolu No: 78D, İskele', '(0392) 330 33 88', true, null, 'Ecz. Pertev Zeki'),
('SELİN ECZANESİ', 'pharmacy', 'Şht. Mustafa Orhan Cad. No:5, İskele', '(0533) 884 86 59', true, null, 'Ecz. Hasan Yorgancı'),
('SEVİLAY PIRLANTA ECZANESİ', 'pharmacy', 'Şht. Davut Sadık Sok., İskele', '(0392) 371 35 02', true, null, 'Ecz. Sevilay Pırlanta'),
('SULTAN TOPEL ECZANESİ', 'pharmacy', 'Makenzi Cad. No: 6, İskele', '(0392) 330 17 20', true, null, 'Ecz. Sultan Topel'),
-- KARPAZ
('BESİM SEVİNDİK ECZANESİ', 'pharmacy', '8 Ağustos Cad., Yeni Erenköy, Karpaz', '(0533) 855 72 12', true, null, 'Ecz. Besim Sevindik'),
('FATMA KAHYAOĞLU ECZANESİ', 'pharmacy', 'Çayırova, İskele, Karpaz', '(0533) 821 96 06', true, null, 'Ecz. İbrahim Kahyaoğlu'),
('KARPAZIN ECZANESİ', 'pharmacy', 'Şht. Mustafa H. Akdeniz Sokak No: 4, Yenierenköy, Karpaz', '(0539) 112 38 02', true, null, 'Ecz. Şenay Mimar'),
('MELEK İBRAHİM ECZANESİ', 'pharmacy', 'Öztürk Cad. No: 10, Mehmetçik, Karpaz', '(0392) 375 53 66', true, null, 'Ecz. Şifa Cömert'),
('OLGUN KAHYAOĞLU ECZANESİ', 'pharmacy', 'Ada Cad. Bafra No: 37/E, Mehmetçik, Karpaz', '(0533) 849 99 46', true, null, 'Ecz. Melek Kahyaoğlu'),
('SAKİNER ECZANESİ', 'pharmacy', 'Yeni Erenköy, Karpaz', '(0392) 374 43 56', true, null, 'Ecz. Ahmet Canan Elkıran');
