-- Duty notification cron jobs
-- These are already live in Supabase (cron.job table). This file is documentation only.
-- To verify: SELECT jobname, schedule FROM cron.job WHERE jobname ILIKE '%duty%';
--
-- All times UTC. TRNC is UTC+3.
--
-- Mon/Tue/Wed/Fri at 14:00 UTC = 17:00 TRNC (30 min before 17:30 close)
-- select cron.schedule('duty-notif-mtwf', '0 14 * * 1,2,3,5', $$
--   select net.http_post(url:='...', headers:='...', body:='{}');
-- $$);
--
-- Thu/Sat at 10:00 UTC = 13:00 TRNC (30 min before 13:30 close)
-- select cron.schedule('duty-notif-thu-sat', '0 10 * * 4,6', $$
--   select net.http_post(url:='...', headers:='...', body:='{}');
-- $$);
--
-- Sunday at 05:00 UTC = 08:00 TRNC (at pharmacy open time)
-- select cron.schedule('duty-notif-sun', '0 5 * * 0', $$
--   select net.http_post(url:='...', headers:='...', body:='{}');
-- $$);
