-- ═══ reviews_appointment_id_key becomes partial too ════════════════════════
--
-- ⚠ THIS FILE IS A WIDENING OF THE AGREED SCOPE. Phase 2 item 4 named exactly one index,
--   `reviews_customer_facility_unique`, which 20260928 already swapped. This is the
--   SECOND unique on `reviews`, and it is in its own file so it can be dropped without
--   touching anything else. Read the next paragraph before deciding.
--
-- ─── WHY THE FEATURE DEAD-ENDS WITHOUT IT ───────────────────────────────────
--
-- `reviews` carries TWO uniques, not one (20260718_capture_1:97-98):
--     reviews_customer_facility_unique  (customer_id, facility_id)   ← swapped by 20260928
--     reviews_appointment_id_key        (appointment_id)             ← this file
--
-- ProfileScreen decides "you have already reviewed this booking" from what it can READ,
-- and 20260928 makes a soft-deleted review unreadable to its own author. So immediately
-- after deleting, the review form is offered again for that same booking — and the INSERT
-- hits the still-global appointment unique and fails with a raw 23505 that no screen maps
-- to copy. The user is shown the form, fills it in, and is refused by a Postgres error.
--
-- That is not an edge case; it is the first thing anyone does after deleting a review.
-- Swapping only the (customer, facility) unique fixes half a path.
--
-- ─── WHAT IT CHANGES, EXACTLY ───────────────────────────────────────────────
--
-- Before: one review per appointment, ever.
-- After:  one LIVE review per appointment. Deleted rows keep their evidence trail but
--         stop occupying the slot. Combined with 20260928's index the invariant is
--         "one live review per appointment AND one live review per (customer, facility)",
--         which is the rule 20260701 was actually written to express — it just had no way
--         to say "live" before deleted_at existed.
--
-- If you would rather NOT allow re-reviewing after a delete, do not apply this file, and
-- instead make the delete affordance in ProfileScreen a one-time action that leaves the
-- booking marked as reviewed. That is a coherent product too — it is just not the one
-- 20260928 implies.

SET ROLE postgres;
BEGIN;

ALTER TABLE public.reviews DROP CONSTRAINT IF EXISTS reviews_appointment_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS reviews_appointment_live_uniq
  ON public.reviews (appointment_id)
  WHERE deleted_at IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes
                  WHERE schemaname='public' AND indexname='reviews_appointment_live_uniq'
                    AND indexdef ILIKE '%deleted_at IS NULL%') THEN
    RAISE EXCEPTION 'reviews_appointment_live_uniq is missing or is not partial';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='reviews_appointment_id_key') THEN
    RAISE EXCEPTION 'the old global appointment unique is still present';
  END IF;
  -- Depends on 20260928. Asserted rather than assumed: applied out of order, the index
  -- above would be created on a column that does not exist and the error would point at
  -- this file rather than at the missing prerequisite.
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema='public' AND table_name='reviews' AND column_name='deleted_at') THEN
    RAISE EXCEPTION 'apply 20260928_ugc_soft_delete.sql first';
  END IF;
  RAISE NOTICE 'appointment unique is now partial';
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260929_reviews_appointment_unique_partial.sql', 'df13e7342f50a3893e1b039b7ab8799176d705f026bc52fe39505d1cecdff69a')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- No ADD COLUMN here, so no schema-cache reload: an index is invisible to PostgREST.

-- ─── Verify ─────────────────────────────────────────────────────────────────
--   SELECT indexname, indexdef FROM pg_indexes
--    WHERE schemaname='public' AND tablename='reviews' ORDER BY indexname;
--   -- expect BOTH …_live_uniq indexes, both carrying WHERE (deleted_at IS NULL)
--
-- ─── Rollback ───────────────────────────────────────────────────────────────
--   DROP INDEX public.reviews_appointment_live_uniq;
--   ALTER TABLE public.reviews ADD CONSTRAINT reviews_appointment_id_key UNIQUE (appointment_id);
--   -- ⚠ fails if any appointment has picked up a second review since this was applied
--   DELETE FROM public.schema_migrations_applied
--    WHERE filename = '20260929_reviews_appointment_unique_partial.sql';
