-- ─── towing_companies.phone_secondary — a fallback number ────────────────────
--
-- WHY: a tow firm's first number rings out often enough that a fallback is worth
-- carrying. Three of the four launch firms have a second number, so this is a pattern
-- in the trade, not a one-off for one listing.
--
-- WHAT IT MUST NOT DO: `Ara` stays ONE TAP TO ONE NUMBER. At the moment somebody presses
-- it they are at the roadside with nothing to choose between — two identical-looking
-- numbers and no basis for preferring either. A chooser modal would tax the majority
-- whose first call connects, in order to help the minority whose does not. The second
-- number is therefore a small secondary affordance (a text link under the call button on
-- the card, a separate contact row on the detail page), never a fork in the primary path.
-- Revisit only with device evidence, not on principle.
--
-- NULLABLE, no default, no backfill. NULL means "this firm has one number", which is the
-- common case and the correct reading of an absent value. The UI renders nothing at all
-- when it is NULL — no empty row, no dead link.
--
-- Not indexed and not searchable: `search_content` matches on name only, and a phone
-- number is something you dial, not something you look a firm up by.
--
-- FORMAT: same as `phone` — E.164 with spaces for readability, e.g. '+90 533 861 00 46'.
-- The client strips whitespace for `tel:` and all non-digits for `wa.me`, so the stored
-- form is free to stay human-readable.
--
-- ADDITIVE + idempotent. SET ROLE postgres is REQUIRED: ALTER TABLE needs the owner.

SET ROLE postgres;
BEGIN;

ALTER TABLE public.towing_companies ADD COLUMN IF NOT EXISTS phone_secondary text;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260908_towing_phone_secondary.sql', 'ac45c7b0ac330781ecc014ab217ab58e81e6cc9744c830c6d969ec20ff2065a6')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- MANDATORY on every ADD COLUMN: without it a stale PostgREST cache reports 42703
-- "column does not exist" through the REST API even though Postgres has the column —
-- which would break the towing list query outright, since it selects *.
NOTIFY pgrst, 'reload schema';

-- ─── Verification — ONE block, run after applying (Role = postgres) ──────────
-- Expect all four columns 'OK'. Nothing persists.
--
-- BEGIN;
-- INSERT INTO public.towing_companies
--   (name, slug, phone, phone_secondary, base_region, coverage_regions, vehicle_classes)
-- VALUES ('Two numbers','zz-two-num','+90 533 000 00 00','+90 533 111 11 11',
--         'nicosia',ARRAY['nicosia'],ARRAY['car']);
-- INSERT INTO public.towing_companies
--   (name, slug, phone, base_region, coverage_regions, vehicle_classes)
-- VALUES ('One number','zz-one-num','+90 533 000 00 00','nicosia',ARRAY['nicosia'],ARRAY['car']);
-- SELECT
--   (SELECT CASE WHEN count(*)=1 THEN 'OK' ELSE 'FAIL <- column missing' END
--      FROM information_schema.columns
--     WHERE table_schema='public' AND table_name='towing_companies'
--       AND column_name='phone_secondary' AND data_type='text')      AS column_exists,
--   (SELECT CASE WHEN is_nullable='YES' THEN 'OK' ELSE 'FAIL <- must be nullable' END
--      FROM information_schema.columns
--     WHERE table_schema='public' AND table_name='towing_companies'
--       AND column_name='phone_secondary')                           AS is_nullable,
--   (SELECT CASE WHEN phone_secondary = '+90 533 111 11 11' THEN 'OK' ELSE 'FAIL' END
--      FROM public.towing_companies WHERE slug='zz-two-num')          AS stores_value,
--   -- omitted must be NULL, not '' — the UI keys "has a second number" off NULL
--   (SELECT CASE WHEN phone_secondary IS NULL THEN 'OK' ELSE 'FAIL <- omitted did not land NULL' END
--      FROM public.towing_companies WHERE slug='zz-one-num')          AS omitted_is_null;
-- ROLLBACK;
--
-- Also confirm PostgREST can see it (signed out, from a shell):
--   curl -s -H "apikey: $ANON" \
--     '<project>.supabase.co/rest/v1/towing_companies?select=phone_secondary&limit=1'
--   -- a 200 with [] is correct (no active rows yet); a 42703 means NOTIFY did not land.

-- ─── Rollback ────────────────────────────────────────────────────────────────
--   SET ROLE postgres;
--   ALTER TABLE public.towing_companies DROP COLUMN IF EXISTS phone_secondary;
--   RESET ROLE;
--   NOTIFY pgrst, 'reload schema';
--   DELETE FROM public.schema_migrations_applied WHERE filename = '20260908_towing_phone_secondary.sql';
