-- ═══ answers — a hidden answer is actually hidden ══════════════════════════
--
-- `read answers` (capture_5:27) checks NOTHING about visibility. Its whole USING clause
-- is a join to the parent question asking only *who* you are:
--
--   USING (EXISTS (SELECT 1 FROM questions q
--          WHERE q.id = answers.question_id
--            AND (q.customer_id = auth.uid()
--                 OR (get_my_role() = 'provider' AND <owns the facility>)
--                 OR get_my_role() = 'admin')))
--
-- Two gates are missing, and both are live defects:
--
--   1. `answers.hidden_at` IS NOT CHECKED. An answer an admin removes stays readable to
--      the customer and to the facility's provider. As of 20260927 admin Remove finally
--      writes hidden_at at all — so this is the first moment the gap has any effect, and
--      it would present as "I removed it and it is still there", which is exactly the bug
--      we just spent two days closing on the other three tables.
--
--   2. THE PARENT IS NOT CHECKED EITHER. Hiding or deleting a question leaves its answers
--      readable — the thread's replies survive the thread. An admin removing an abusive
--      Q&A exchange has to remove each answer individually and has no way to know how
--      many there were, because the queue is per-report, not per-thread.
--
-- ─── ORDERING ───────────────────────────────────────────────────────────────
--
-- This was Phase 2 item 2 and is applied THIRD, because it references
-- `questions.deleted_at`, which 20260928 creates. Priority order and apply order differ
-- here; the dependency is asserted below rather than trusted to a filename.

SET ROLE postgres;
BEGIN;

DROP POLICY IF EXISTS "read answers" ON public.answers;
CREATE POLICY "read answers" ON public.answers
  FOR SELECT TO public
  USING (
    (
      hidden_at IS NULL
      AND EXISTS (
        SELECT 1 FROM questions q
        WHERE q.id = answers.question_id
          AND q.hidden_at  IS NULL
          AND q.deleted_at IS NULL
          AND (
            q.customer_id = auth.uid()
            OR (get_my_role() = 'provider'
                AND EXISTS (SELECT 1 FROM facilities f
                             WHERE f.id = q.facility_id
                               AND f.provider_id = auth.uid()))
          )
      )
    )
    -- The answer's author keeps seeing their own, hidden or not — the same courtesy the
    -- review and question policies extend to their authors, and the reason a provider is
    -- not left staring at a thread that silently lost their reply.
    OR provider_id = auth.uid()
    OR get_my_role() = 'admin'
  );

DO $$
DECLARE
  v_cnt int;
  v_names text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema='public' AND table_name='questions' AND column_name='deleted_at') THEN
    RAISE EXCEPTION 'apply 20260928_ugc_soft_delete.sql first — this policy references questions.deleted_at';
  END IF;

  SELECT count(*), string_agg(policyname || ' [' || cmd || ']', ', ' ORDER BY policyname)
    INTO v_cnt, v_names
    FROM pg_policies WHERE schemaname='public' AND tablename='answers';
  RAISE NOTICE 'answers : % policies — %', v_cnt, v_names;
  -- Drop-and-recreate of an existing policy, so the count must be UNCHANGED at 6. A 7
  -- here means the DROP did not match the live policy name and there are now two SELECT
  -- policies — which OR together, and the more permissive one wins. That failure would
  -- leave hidden answers readable while every other check in this file passed.
  IF v_cnt <> 6 THEN
    RAISE EXCEPTION 'answers has % policies, expected 6 — a stale duplicate SELECT policy would silently re-open the gap', v_cnt;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname='public' AND tablename='answers' AND policyname='read answers'
                    AND qual ILIKE '%deleted_at%' AND qual ILIKE '%hidden_at%') THEN
    RAISE EXCEPTION 'read answers is installed but carries neither gate';
  END IF;
  RAISE NOTICE 'answers read gates OK';
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260930_answers_read_gates.sql', '3088c605e4657b1057569a851b6f0037b21bdfe3eb5cab8a78f250c390ab8fa1')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- ─── Verify ─────────────────────────────────────────────────────────────────
--   SELECT policyname, cmd, qual FROM pg_policies
--    WHERE schemaname='public' AND tablename='answers' ORDER BY policyname;   -- 6 rows
--
--   -- behavioural, as the CUSTOMER who asked the question (not as postgres):
--   BEGIN;
--     SET LOCAL ROLE authenticated;
--     SET LOCAL request.jwt.claims = '{"sub":"<customer uuid>","is_anonymous":false}';
--     SELECT count(*) FROM answers WHERE question_id = '<a question with a hidden answer>';
--   ROLLBACK;
--   -- expect the hidden answer to be absent. RESET ROLE before counting anything you
--   -- wrote, or you are asking the question under the policy that forbids the answer.
--
-- ─── Rollback ───────────────────────────────────────────────────────────────
--   Restore the "read answers" body from 20260718_capture_5_rls_policies.sql:27 verbatim.
--   DELETE FROM public.schema_migrations_applied WHERE filename = '20260930_answers_read_gates.sql';
