-- ═══════════════════════════════════════════════════════════════════════════
-- 20261100 — check-ins waitlist blast (module go-live SOP step 10)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- MODULE_FLAGS.checkins went live in production OTA 27cdaa7d (Android 01a1201f), 2026-10-09.
-- notify_module_waitlist('checkins') stamps each waiting row, writes an in-app notification and
-- POSTs an Expo push (pg_net, sent after COMMIT). Runs as postgres: its admin guard allows that.
--
-- A burnt list and an empty list both return 0, so the list is asserted BEFORE (3 waiting,
-- 0 notified — measured 2026-10-08) and AFTER (all 3 stamped today, the call returned 3).
-- Anything else raises and the whole file rolls back: nobody is notified twice or half-way.
--
-- Apply: gh workflow run supabase-migrate -f file=20261100_checkins_waitlist_blast.sql
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  v_total    int;
  v_notified int;
  v_sent     int;
BEGIN
  SELECT count(*), count(*) FILTER (WHERE notified_at IS NOT NULL) INTO v_total, v_notified
    FROM module_waitlist WHERE module = 'checkins';
  IF v_total IS DISTINCT FROM 3 OR v_notified IS DISTINCT FROM 0 THEN
    RAISE EXCEPTION 'REFUSING: checkins waitlist is %/% notified, expected 0/3 — re-measure before sending', v_notified, v_total;
  END IF;

  v_sent := notify_module_waitlist('checkins');

  SELECT count(*) FILTER (WHERE notified_at IS NOT NULL
                           AND (notified_at AT TIME ZONE 'Europe/Istanbul')::date = (now() AT TIME ZONE 'Europe/Istanbul')::date)
    INTO v_notified FROM module_waitlist WHERE module = 'checkins';
  IF v_sent IS DISTINCT FROM 3 OR v_notified IS DISTINCT FROM 3 THEN
    RAISE EXCEPTION 'blast incomplete: function returned %, % of 3 stamped today — rolled back', v_sent, v_notified;
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261100_checkins_waitlist_blast.sql', '48c7fb66ebfba4a616730bcb5890223e27b503602e61969c4c6af7b69d4ddbfc')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;

RESET ROLE;
