-- ═══ Explore — photo_attribution: REGISTRATION OF AN ALREADY-APPLIED COLUMN ═══
--
-- ⚠ THIS MIGRATION DOES NOT INTRODUCE NEW SCHEMA. The `photo_attribution` column was
--   added BY HAND, in the SQL editor, before this file existed — so it ran without a
--   ledger stamp and without an entry in verify_schema.sql. The column was therefore
--   invisible to BOTH drift checks: `migration_ledger_check` had no row to compare, and
--   verify_schema.sql had no token to look for. This file closes that gap.
--
-- It is written to be a SAFE NO-OP against the live database. Every statement is
-- IF NOT EXISTS / CREATE OR REPLACE, so re-running it changes nothing about the column
-- and exists only to land the ledger row at the tail. Run it once, in the SQL editor,
-- Role = postgres. Then `node scripts/migration-ledger.mjs` and re-run
-- supabase/migration_ledger_check.sql — the file should stop being listed.
--
-- ─── WHAT THE COLUMN IS ─────────────────────────────────────────────────────
--
-- KEYED BY PHOTO URL, NOT BY ARRAY INDEX. This is the whole point of the column and the
-- reason it supersedes `photo_credits`:
--
--   {"<photo url>": {"credit": "", "license": "", "license_url": "",
--                    "source_url": "", "source": "commons|unsplash|own|partner"}}
--
-- photo_credits[i] attributes photos[i] positionally, so deleting photos[0] silently
-- re-points every remaining credit to the wrong photo — a legally wrong attribution
-- produced by an ordinary edit, with nothing to detect it. A URL key cannot drift:
-- remove the photo and its entry is simply orphaned, which is inert.
--
-- ─── WHY photo_credits IS NOT DROPPED ───────────────────────────────────────
--
-- It is still the ONLY thing the shipped production JS renders
-- (ExploreProfileScreen renders place.photo_credits[imgIdx] and nothing else), and OTA
-- adoption is not instant. Both columns are written together until the attribution
-- renderer has been live long enough that no meaningful install reads the old path.
-- Dropping photo_credits is a LATER migration, deliberately not this one.
--
-- ─── SCOPE: three tables, on purpose ────────────────────────────────────────
--
-- `places` is the live directory. `beaches` and `landmarks` are the frozen legacy tables
-- that still back search_content's beach/landmark arms, and they keep photo_credits, so
-- they get the same column for symmetry until the DROP-era cleanup removes all three.

SET ROLE postgres;
BEGIN;

ALTER TABLE public.places
  ADD COLUMN IF NOT EXISTS photo_attribution jsonb;
ALTER TABLE public.beaches
  ADD COLUMN IF NOT EXISTS photo_attribution jsonb;
ALTER TABLE public.landmarks
  ADD COLUMN IF NOT EXISTS photo_attribution jsonb;

COMMENT ON COLUMN public.places.photo_attribution IS
  'Per-photo licensing, KEYED BY PHOTO URL (not array index): {"<url>": {credit, license, license_url, source_url, source}}. Supersedes photo_credits, which is positional and mis-attributes when a photo is deleted. NULL = legacy row; readers fall back to photo_credits by index.';
COMMENT ON COLUMN public.beaches.photo_attribution IS
  'See places.photo_attribution. Frozen legacy table — kept in sync until the DROP-era cleanup.';
COMMENT ON COLUMN public.landmarks.photo_attribution IS
  'See places.photo_attribution. Frozen legacy table — kept in sync until the DROP-era cleanup.';

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260917_place_photo_attribution.sql', '4d3391d3d46f01b149296413f7a404475b768ec091d4d0237ba68cd2f8a1b071')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- ADD COLUMN → PostgREST's schema cache must be refreshed, or the REST API reports
-- 42703 "column does not exist" for photo_attribution even though Postgres has it.
-- Harmless to re-issue when the column was already present.
NOTIFY pgrst, 'reload schema';

-- ─── Verification (Role = postgres) ─────────────────────────────────────────
--   SELECT table_name, data_type, is_nullable
--     FROM information_schema.columns
--    WHERE column_name = 'photo_attribution' AND table_schema = 'public'
--    ORDER BY table_name;
--   -- expect 3 rows: beaches, landmarks, places — all jsonb, all YES.
--
-- Then run supabase/verify_schema.sql (the 0917 tokens are registered there) and
-- supabase/migration_ledger_check.sql (this file must no longer be listed as missing).

-- ─── Rollback ───────────────────────────────────────────────────────────────
-- Do NOT run casually: the seed script writes this column, so dropping it discards real
-- licensing data that cannot be reconstructed from photo_credits (which carries no
-- license URI and no source URL).
--   SET ROLE postgres; BEGIN;
--   ALTER TABLE public.places    DROP COLUMN IF EXISTS photo_attribution;
--   ALTER TABLE public.beaches   DROP COLUMN IF EXISTS photo_attribution;
--   ALTER TABLE public.landmarks DROP COLUMN IF EXISTS photo_attribution;
--   DELETE FROM public.schema_migrations_applied WHERE filename = '20260917_place_photo_attribution.sql';
--   COMMIT; RESET ROLE;
--   NOTIFY pgrst, 'reload schema';
