-- ═══ institutions — 12 universities in CY, seeded INACTIVE (generated) ═══════
--
-- Generated by scripts/gen-institution-seeds.mjs from data/institutions/cy.csv.
-- Do not hand-edit: change the CSV (or curate.py) and regenerate before the apply; an applied
-- file is never edited. Ids are UUIDv5 of 'CY|<source_key>' (see the generator).
--
-- Sources:
--   https://www.highereducation.ac.cy/en/idrymata/panepistimio-kiprou
--   https://www.highereducation.ac.cy/en/idrymata/tepak-en
--   https://www.highereducation.ac.cy/en/idrymata/anoichto-panepistimio-kyprou-en
--   https://www.highereducation.ac.cy/en/idrymata/frederick-universities
--   https://www.highereducation.ac.cy/en/idrymata/european-university-cyprus-en
--   https://www.highereducation.ac.cy/en/idrymata/panepistimio-lefkosias-en
--   https://www.highereducation.ac.cy/en/idrymata/neapolis-university-cyprus
--   https://www.highereducation.ac.cy/en/idrymata/uclan-panepistimio-en
--   https://www.highereducation.ac.cy/en/idrymata/philips-university-en
--   https://www.highereducation.ac.cy/en/idrymata/aucy-university-en
--   https://www.highereducation.ac.cy/en/idrymata/panepistimio-limassol-en
--   https://www.highereducation.ac.cy/en/idrymata/panepistimio-american-university-of-beirut-en
--
-- is_active = false: nothing here is visible until the activation migration runs (module
-- go-live SOP). sort_order 500: below every TRNC row, above Other (999).
--
-- RE-RUN: ON CONFLICT (id) DO NOTHING, so a later edit to one of these rows is never
-- reverted. The checks below assert the ids exist in CY, not their current values.
--
-- EXECUTION: supabase-migrate workflow (dry, then -f apply=true). Requires 20261095.

SET ROLE postgres;

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'institutions_country_name_unique'
                  AND conrelid = 'public.institutions'::regclass) THEN
    RAISE EXCEPTION 'REFUSING: 20261095 (institutions.country, per-country names) is not applied. Nothing applied.';
  END IF;
END $$;

-- A name already used in CY by a DIFFERENT id would make the INSERT fail with a bare
-- 23505; say which instead.
DO $$
DECLARE v_clash text;
BEGIN
  SELECT string_agg(i.name, ' · ') INTO v_clash
    FROM public.institutions i
    JOIN (VALUES
      ('9eb5dba7-f562-548b-a398-3d91b75689e6'::uuid, 'University of Cyprus'),
      ('c4f2c066-835d-52db-abea-d4e36ca92ee0'::uuid, 'Cyprus University of Technology'),
      ('da2a3802-96f5-5c0d-9223-407dfc4ea08b'::uuid, 'Open University of Cyprus'),
      ('1c406120-7285-5435-b8b4-b8309e090ddc'::uuid, 'Frederick University'),
      ('85d48338-e785-53e8-bc2a-b4e6da794b3d'::uuid, 'European University Cyprus'),
      ('c0851764-71bf-5d21-b037-14ff0139dc19'::uuid, 'University of Nicosia'),
      ('1dbc5b70-15f8-50a2-8270-7bcef9add0e2'::uuid, 'Neapolis University Pafos'),
      ('831848be-4da8-5ad9-8ebc-745e25f0c2cf'::uuid, 'University of Central Lancashire Cyprus'),
      ('49b18428-537e-5665-a159-483d54236bba'::uuid, 'Philips University'),
      ('7682672a-88a8-5d81-9d1f-0ecbeb83a6ae'::uuid, 'American University of Cyprus'),
      ('f6f9464f-d155-5f98-b635-08252fbd3422'::uuid, 'University of Limassol'),
      ('850866ed-c2f4-5833-ad50-7d2e8d5c84d9'::uuid, 'American University of Beirut – Mediterraneo')
    ) AS v(id, name) ON v.name = i.name AND i.country = 'CY' AND i.id <> v.id;
  IF v_clash IS NOT NULL THEN
    RAISE EXCEPTION 'REFUSING: already in CY under another id: %. Nothing applied.', v_clash;
  END IF;
END $$;

-- Against the TRNC rows: the names this seed shares with an XN row must be EXACTLY the
-- reviewed allowance ([]). Printed either way.
DO $$
DECLARE v_shared text;
BEGIN
  SELECT coalesce(string_agg(DISTINCT i.name, ' · ' ORDER BY i.name), '') INTO v_shared
    FROM public.institutions i
    JOIN (VALUES
      ('University of Cyprus'),
      ('Cyprus University of Technology'),
      ('Open University of Cyprus'),
      ('Frederick University'),
      ('European University Cyprus'),
      ('University of Nicosia'),
      ('Neapolis University Pafos'),
      ('University of Central Lancashire Cyprus'),
      ('Philips University'),
      ('American University of Cyprus'),
      ('University of Limassol'),
      ('American University of Beirut – Mediterraneo')
    ) AS v(name) ON lower(v.name) = lower(i.name) AND i.country = 'XN';
  RAISE NOTICE 'names shared with TRNC rows: [%]', v_shared;
  IF v_shared IS DISTINCT FROM '' THEN
    RAISE EXCEPTION 'REFUSING: names shared with TRNC rows are [%], reviewed allowance is []. Nothing applied.', v_shared;
  END IF;
END $$;

INSERT INTO public.institutions (id, name, country, city_name, website_url, sort_order, is_active) VALUES
  ('9eb5dba7-f562-548b-a398-3d91b75689e6', 'University of Cyprus', 'CY', 'Nicosia', 'https://www.ucy.ac.cy', 500, false),
  ('c4f2c066-835d-52db-abea-d4e36ca92ee0', 'Cyprus University of Technology', 'CY', 'Limassol', 'https://www.cut.ac.cy', 500, false),
  ('da2a3802-96f5-5c0d-9223-407dfc4ea08b', 'Open University of Cyprus', 'CY', 'Nicosia', 'https://www.ouc.ac.cy', 500, false),
  ('1c406120-7285-5435-b8b4-b8309e090ddc', 'Frederick University', 'CY', NULL, 'https://frederick.ac.cy', 500, false),
  ('85d48338-e785-53e8-bc2a-b4e6da794b3d', 'European University Cyprus', 'CY', 'Nicosia', 'https://www.euc.ac.cy', 500, false),
  ('c0851764-71bf-5d21-b037-14ff0139dc19', 'University of Nicosia', 'CY', 'Nicosia', 'https://www.unic.ac.cy', 500, false),
  ('1dbc5b70-15f8-50a2-8270-7bcef9add0e2', 'Neapolis University Pafos', 'CY', 'Paphos', 'https://www.nup.ac.cy', 500, false),
  ('831848be-4da8-5ad9-8ebc-745e25f0c2cf', 'University of Central Lancashire Cyprus', 'CY', 'Larnaca', 'https://www.uclancyprus.ac.cy', 500, false),
  ('49b18428-537e-5665-a159-483d54236bba', 'Philips University', 'CY', 'Nicosia', 'https://philipsuni.ac.cy', 500, false),
  ('7682672a-88a8-5d81-9d1f-0ecbeb83a6ae', 'American University of Cyprus', 'CY', 'Larnaca', 'https://www.aucy.ac.cy', 500, false),
  ('f6f9464f-d155-5f98-b635-08252fbd3422', 'University of Limassol', 'CY', NULL, 'https://www.uol.ac.cy', 500, false),
  ('850866ed-c2f4-5833-ad50-7d2e8d5c84d9', 'American University of Beirut – Mediterraneo', 'CY', 'Paphos', 'https://www.aubmed.ac.cy', 500, false)
ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE
  v_here   int;
  v_total  int;
BEGIN
  SELECT count(*) INTO v_here FROM public.institutions
   WHERE country = 'CY' AND id IN ('9eb5dba7-f562-548b-a398-3d91b75689e6','c4f2c066-835d-52db-abea-d4e36ca92ee0','da2a3802-96f5-5c0d-9223-407dfc4ea08b','1c406120-7285-5435-b8b4-b8309e090ddc','85d48338-e785-53e8-bc2a-b4e6da794b3d','c0851764-71bf-5d21-b037-14ff0139dc19','1dbc5b70-15f8-50a2-8270-7bcef9add0e2','831848be-4da8-5ad9-8ebc-745e25f0c2cf','49b18428-537e-5665-a159-483d54236bba','7682672a-88a8-5d81-9d1f-0ecbeb83a6ae','f6f9464f-d155-5f98-b635-08252fbd3422','850866ed-c2f4-5833-ad50-7d2e8d5c84d9');
  IF v_here <> 12 THEN
    RAISE EXCEPTION 'expected all 12 ids in CY, found %. Nothing applied.', v_here;
  END IF;
  SELECT count(*) INTO v_total FROM public.institutions WHERE country = 'CY';
  IF v_total <> 12 THEN
    RAISE EXCEPTION 'CY holds % rows, expected exactly 12 (rows from elsewhere?). Nothing applied.', v_total;
  END IF;
  IF (SELECT count(*) FROM public.institutions WHERE country = 'XN') <> 24 THEN
    RAISE EXCEPTION 'the TRNC rows changed under this seed. Nothing applied.';
  END IF;
  RAISE NOTICE '20261097_institutions_seed_cy.sql: 12 rows in CY (% active).',
    (SELECT count(*) FROM public.institutions WHERE country = 'CY' AND is_active);
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261097_institutions_seed_cy.sql', '737f653a4a1d71f5bad527ab423d5797352b34115e48eeb4dc6908070969aeb9')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;

RESET ROLE;
