-- ─── 20261085 — pharmacy_coords: the last four roster pharmacies get pins ────
--
-- 20261079 left exactly four rows without coordinates (asserted there by name). Probed
-- read-only 2026-10-06 (supabase/readonly/duty_pharmacy_coverage.sql): all four exist,
-- lat/lng NULL, source NULL, under the region each one carries in the forward roster.
--
-- Recorded like 20261079's 14 manual pins: source = 'manual', verified = true. Provenance
-- (Berke, 2026-10-06):
--   • SERVET GÖKŞİN — Berke's own manual pin.
--   • GİZEM KARAHASAN, NERİMAN KARATAÇ, VADİLİ — coordinates from eczaneler.gen.tr, each
--     visually confirmed by Berke on Google Maps.
--
-- Only lat, lng, source and verified change; region is matched, never written. No policy,
-- grant or other row is touched. Duty screen effect: these four roster names gain a
-- distance (offline, through utils/dutyFacilityMatch.js: 316 + 4 via pharmacy_coords).

SET ROLE postgres;

BEGIN;

-- ─── Pre-condition: the four rows exist under the expected region ───────────
DO $$
DECLARE n int; names text;
BEGIN
  SELECT count(*), string_agg(c.name || ' (' || coalesce(c.region, 'NULL') || ')', ', ') INTO n, names
    FROM public.pharmacy_coords c
    JOIN (VALUES
      ('GİZEM KARAHASAN ECZANESİ', 'Gazimağusa'),
      ('NERİMAN KARATAÇ ECZANESİ', 'Lefkoşa'),
      ('SERVET GÖKŞİN ECZANESİ',   'Alt Mesarya'),
      ('VADİLİ ECZANESİ',          'Alt Mesarya')
    ) v(name, region) ON c.name_key = public.pharmacy_name_key(v.name) AND c.region IS NOT DISTINCT FROM v.region;
  IF n <> 4 THEN RAISE EXCEPTION '20261085: % of 4 rows found under the expected region: %', n, names; END IF;
END $$;

UPDATE public.pharmacy_coords c
   SET lat = v.lat, lng = v.lng, source = 'manual', verified = true
  FROM (VALUES
    ('GİZEM KARAHASAN ECZANESİ', 'Gazimağusa',  35.15968, 33.89154),
    ('NERİMAN KARATAÇ ECZANESİ', 'Lefkoşa',     35.20914, 33.37874),
    ('SERVET GÖKŞİN ECZANESİ',   'Alt Mesarya', 35.11681, 33.56747),
    ('VADİLİ ECZANESİ',          'Alt Mesarya', 35.13766, 33.65062)
  ) v(name, region, lat, lng)
 WHERE c.name_key = public.pharmacy_name_key(v.name) AND c.region = v.region;

-- ─── Assertions — any failure rolls back the whole file ──────────────────────
DO $$
DECLARE n int; names text; dist text;
BEGIN
  SELECT count(*) INTO n FROM public.pharmacy_coords;
  IF n <> 332 THEN RAISE EXCEPTION '20261085: % rows, expected 332', n; END IF;
  SELECT count(*), string_agg(name, ', ' ORDER BY name) INTO n, names FROM public.pharmacy_coords WHERE lat IS NULL OR lng IS NULL;
  IF n <> 0 THEN RAISE EXCEPTION '20261085: % rows still without coordinates: %', n, names; END IF;
  SELECT string_agg(coalesce(source, 'NULL') || ':' || verified || ':' || k, ', ' ORDER BY source COLLATE "C") INTO dist
    FROM (SELECT source, verified, count(*) AS k FROM public.pharmacy_coords GROUP BY 1, 2) x;
  IF dist IS DISTINCT FROM 'facilities:false:314, manual:true:18' THEN
    RAISE EXCEPTION '20261085: rows by source/verified: %', dist;
  END IF;
  -- The four carry exactly the given pins (a swapped or mistyped pair reads here).
  SELECT count(*) INTO n FROM public.pharmacy_coords c
    JOIN (VALUES
      ('GİZEM KARAHASAN ECZANESİ', 35.15968, 33.89154),
      ('NERİMAN KARATAÇ ECZANESİ', 35.20914, 33.37874),
      ('SERVET GÖKŞİN ECZANESİ',   35.11681, 33.56747),
      ('VADİLİ ECZANESİ',          35.13766, 33.65062)
    ) v(name, lat, lng) ON c.name_key = public.pharmacy_name_key(v.name)
   WHERE c.lat = v.lat AND c.lng = v.lng AND c.source = 'manual' AND c.verified;
  IF n <> 4 THEN RAISE EXCEPTION '20261085: % of 4 rows carry their manual pin', n; END IF;
  SELECT count(*), string_agg(name, ', ') INTO n, names FROM public.pharmacy_coords
   WHERE NOT (lat BETWEEN 34.9 AND 35.75 AND lng BETWEEN 32.6 AND 34.65);
  IF n <> 0 THEN RAISE EXCEPTION '20261085: % pins outside North Cyprus: %', n, names; END IF;
  -- Region untouched: 20261080's end-state distribution still holds.
  SELECT string_agg(region || '=' || k, ', ' ORDER BY region COLLATE "C") INTO dist
    FROM (SELECT coalesce(region, 'NULL') AS region, count(*) AS k FROM public.pharmacy_coords GROUP BY 1) x;
  IF dist IS DISTINCT FROM 'Alt Mesarya=13, Gazimağusa=67, Girne=66, Güzelyurt=18, Karpaz=7, Lefke=10, Lefkoşa=130, Üst Mesarya=6, İskele=15' THEN
    RAISE EXCEPTION '20261085: region distribution is %', dist;
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261085_pharmacy_coords_last_four_pins.sql', '4a7c27ab2122b0bd8d8ef730b66375c7f160d1a750bf64d6a35efa95815d9818')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
