-- ═══════════════════════════════════════════════════════════════════════════
-- 20261094 — remove check-ins PREVIEW TEST DATA before the flag flip (Berke, 2026-10-08)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Applied BEFORE MODULE_FLAGS.checkins flips, so every check-ins row in production is test data
-- from ADA Preview (supabase/readonly/checkins_test_data.sql, run 2026-10-08):
--   • the .env test account 39a24218… ("Ustun"): notice accepted 2026-10-08 15:42 UTC, v2026-10-07
--   • google_places_usage: 8 rows (that account + the GLOBAL counters, 2026-10-07/08)
--   • google_place_pins: 1 orphan row (ChIJM_Rmn-4Q3hQRzuEYIrEEECA — its check-in already deleted)
--   • checkins: 0 rows; places submitted since 2026-10-07: 0
-- It REFUSES (nothing changes) if any check-in, usage row or notice stamp belongs to anyone else:
-- that would mean a real user's data, and this file must never touch one.
--
-- Apply: gh workflow run supabase-migrate -f file=20261094_checkins_test_data_cleanup.sql
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  v_test  uuid := '39a24218-a9a1-4cb8-965a-c217c09b9f94';
  v_nil   uuid := '00000000-0000-0000-0000-000000000000';
  v_n     int;
BEGIN
  SELECT count(*) INTO v_n FROM checkins WHERE user_id IS DISTINCT FROM v_test;
  IF v_n > 0 THEN RAISE EXCEPTION 'REFUSING: % check-in(s) by someone other than the test account', v_n; END IF;
  SELECT count(*) INTO v_n FROM google_places_usage WHERE user_id NOT IN (v_test, v_nil);
  IF v_n > 0 THEN RAISE EXCEPTION 'REFUSING: % usage row(s) of another user', v_n; END IF;
  SELECT count(*) INTO v_n FROM profiles WHERE checkins_notice_at IS NOT NULL AND id IS DISTINCT FROM v_test;
  IF v_n > 0 THEN RAISE EXCEPTION 'REFUSING: % other account(s) accepted the check-in notice', v_n; END IF;

  DELETE FROM checkins WHERE user_id = v_test;
  DELETE FROM google_place_pins;          -- none can be visible: no check-in remains
  DELETE FROM google_places_usage;        -- the test account + GLOBAL only (asserted above)
  PERFORM set_config('app.trusted_checkin_notice', 'on', true);
  UPDATE profiles SET checkins_notice_at = NULL, checkins_notice_version = NULL, checkins_public = NULL
   WHERE id = v_test;
  PERFORM set_config('app.trusted_checkin_notice', 'off', true);

  -- Read back: nothing check-ins-shaped is left anywhere.
  IF (SELECT count(*) FROM checkins) <> 0 OR (SELECT count(*) FROM google_place_pins) <> 0
     OR (SELECT count(*) FROM google_places_usage) <> 0
     OR (SELECT count(*) FROM profiles WHERE checkins_notice_at IS NOT NULL OR checkins_public IS NOT NULL) <> 0 THEN
    RAISE EXCEPTION 'cleanup incomplete — rolled back';
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261094_checkins_test_data_cleanup.sql', '4eb789db240e22b6e97795fe69eb7e345ea1305b90d589326f8a039759e7495c')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;

RESET ROLE;
