-- ═══ Signup is customer-only ═══════════════════════════════════════════════
--
-- Product decision 2026-08-27: the account-type picker is removed from signup. The
-- "Health Professional" and "Event Manager" options are no longer self-serve. Both roles
-- are still granted by an admin AFTER signup, from AdminScreen.
--
-- ─── ALREADY APPLIED — THIS FILE IS THE RECORD, NOT THE CHANGE ──────────────
--
-- The function below was applied by hand in the SQL Editor before this file existed, and
-- re-applied once to scrub the comment block (see the note at the bottom). DO NOT RUN IT
-- AGAIN expecting it to change anything — it is here so the repo carries what production
-- runs, and so migration_ledger_check can attest that the two match.
--
-- ─── WHY IGNORE THE METADATA RATHER THAN ALLOW-LIST IT ──────────────────────
--
-- 20260719 replaced a straight copy of raw_user_meta_data->>'role' with an allow-list of
-- ('customer','provider','organizer'). That was the right fix while three roles were
-- selectable. Now that only one is, an allow-list is the wrong shape: it still READS
-- client-supplied metadata and still has to be correct about what it permits. Ignoring
-- the field entirely removes the decision instead of narrowing it — there is no longer
-- any input for a crafted `supabase.auth.signUp({ options: { data: { role: … } } })` to
-- reach. The client is not a boundary and this stops pretending it might be.
--
-- ─── WHAT IS DELIBERATELY *NOT* CHANGED ─────────────────────────────────────
--
-- profiles_role_check STILL ALLOWS ALL SIX VALUES. Narrowing it would break the admin
-- promotion path (AdminScreen.js:1692/1695/2586/2763) and orphan live accounts. As of
-- today: 176 customer, 8 provider, 2 admin, 2 organizer. The 10 non-customer accounts
-- keep every screen and every RLS grant they have now — App.js's six role branches
-- (:976-1063) are untouched, as are the provider-role policies in capture_5 and
-- get_customer_contacts().
--
-- This migration narrows who can BECOME a role at signup. It does not narrow what a role
-- IS, and it takes nothing away from anyone who already holds one.
--
-- Apply: already done. Then `node scripts/migration-ledger.mjs` and run the stamp INSERT
-- below once by hand, since the DDL landed before the file carried its stamp.

SET ROLE postgres;
BEGIN;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- 2026-08-27: signup is customer-only.
  -- Every new account is created as 'customer'. Client-supplied signup
  -- metadata is ignored entirely rather than allow-listed, so passing a
  -- role straight to the auth API cannot escalate.
  -- All privileged roles are granted by an admin after signup.
  -- Existing non-customer accounts are untouched by this change.
  INSERT INTO public.profiles (id, role)
  VALUES (new.id, 'customer');

  RETURN new;
END;
$function$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260827_signup_customer_only.sql', '06126e0df0838af6e2ba149d9d339a2271d08be5e2abbeefdfda8b9c77a20fd5')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- No ADD COLUMN, so no PostgREST schema-cache reload is required.

-- ─── ⚠ THE COMMENT BLOCK ABOVE IS LOAD-BEARING. DO NOT REWORD IT. ───────────
--
-- pg_get_functiondef() returns the ENTIRE definition, comments included. The
-- 0827 drift token in verify_schema.sql asserts, among other things:
--
--     pg_get_functiondef(oid) NOT ILIKE '%organizer%'
--     pg_get_functiondef(oid) NOT ILIKE '%raw_user_meta_data%'
--
-- The first version of this function explained itself by naming the allow-list it
-- replaced — the words "organizer" and "raw_user_meta_data" appeared in its PROSE while
-- being absent from its CODE. Both clauses were false against a function whose behaviour
-- was exactly right. It was re-applied with the comment above, which says the same thing
-- without either word.
--
-- So: a token asserting the ABSENCE of a string in a function body is really asserting
-- its absence from the comments too. Either keep the prose clear of the words the token
-- forbids (done here), or anchor the token on code that cannot appear in prose. Rewording
-- this block to mention the old allow-list will turn the drift check red without changing
-- a single line of behaviour.

-- ─── Verification (Role = postgres) ─────────────────────────────────────────
--   -- 1. all three token clauses, the same ones verify_schema asserts:
--   SELECT pg_get_functiondef(oid) ILIKE '%''customer''%'          AS inserts_customer,
--          pg_get_functiondef(oid) NOT ILIKE '%organizer%'         AS no_organizer,
--          pg_get_functiondef(oid) NOT ILIKE '%raw_user_meta_data%' AS ignores_metadata
--     FROM pg_proc WHERE proname = 'handle_new_user';
--   -- expect t / t / t
--
--   -- 2. the trigger still fires it:
--   SELECT tgname, tgenabled FROM pg_trigger
--    WHERE tgrelid = 'auth.users'::regclass AND NOT tgisinternal;
--   -- expect on_auth_user_created, enabled ('O')
--
--   -- 3. the CHECK constraint is UNCHANGED — all six values still permitted, or the
--   --    admin promotion path is broken:
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = 'profiles_role_check';
--   -- expect customer, provider, admin, organizer, estate_agent, home_service_provider
--
--   -- 4. WATCH IT IGNORE THE ROLE. A signup carrying role='provider' must still land as
--   --    'customer'. Run against a THROWAWAY email, then delete the user.
--   --    (The client no longer sends the field at all; this proves the API cannot either.)

-- ─── Rollback — restores self-serve provider/organizer signup ───────────────
-- Only if the product decision is reversed. The client picker must come back in the same
-- change, or this re-opens a path nothing in the app can reach.
--   CREATE OR REPLACE FUNCTION public.handle_new_user()
--    RETURNS trigger
--    LANGUAGE plpgsql
--    SECURITY DEFINER
--    SET search_path TO 'public'
--   AS $function$
--   DECLARE
--     v_role text := coalesce(new.raw_user_meta_data->>'role', 'customer');
--   BEGIN
--     IF v_role NOT IN ('customer', 'provider', 'organizer') THEN
--       v_role := 'customer';
--     END IF;
--     INSERT INTO public.profiles (id, role)
--     VALUES (new.id, v_role);
--     RETURN new;
--   END;
--   $function$;
--
--   -- and revert the verify_schema token to the 0719 allow-list form.
--   DELETE FROM public.schema_migrations_applied
--    WHERE filename = '20260827_signup_customer_only.sql';
