-- ═══════════════════════════════════════════════════════════════════════════
-- 20261058 — events.last_seen_at: proof that a Gişe Kıbrıs sync RAN
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Run 36412513281 (2026-09-28) failed at "Content health" with every real step green:
-- fetch, transform, probe, import and sweep all succeeded. check-gisekibris-staleness.mjs
-- reads max(events.updated_at) as "did the import run", but the importer writes only rows
-- whose content CHANGED — unchanged rows are counted and skipped. So max(updated_at) is
-- "when the partner last edited something", and two quiet partner days read as a dead
-- scheduler. Measured: newest updated_at was 50.2h old, which is the start of run
-- 36232527827 (2026-09-26 09:21Z), the last run that had a diff.
--
-- Same shape as properties.last_seen_at (20260904): stamped on EVERY row present in the
-- feed on EVERY run, changed or not. updated_at keeps meaning "content changed" — touching
-- it on unchanged rows would destroy that signal to fix a monitor.
--
-- Written by service_role only (the importer). ev_guard_write guards callers WITH an
-- auth.uid(); service_role has none, and the column is not one the guard names.
-- NULL for every non-feed event, by design.
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

ALTER TABLE public.events ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;

COMMENT ON COLUMN public.events.last_seen_at IS
  'Partner-feed rows only. Stamped on EVERY sync run, whether or not anything changed, '
  'so max(last_seen_at) proves the importer ran. updated_at means content changed; '
  'do not conflate them. Read by scripts/check-gisekibris-staleness.mjs.';

DO $$
DECLARE v_type text;
BEGIN
  SELECT data_type INTO v_type
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'last_seen_at';
  IF v_type IS DISTINCT FROM 'timestamp with time zone' THEN
    RAISE EXCEPTION 'events.last_seen_at missing or wrong type after ADD: %', coalesce(v_type, '(absent)');
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261058_events_last_seen_at.sql', '69b296700efdf532f1beaedefad4f5232332884e536292856e67504516d4439e')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

NOTIFY pgrst, 'reload schema';
