-- ─── 20261080 — pharmacy_coords: 'Mesarya' → the pharmacy's KTEB sub-region ──
--
-- pharmacy_coords' pre-repo rows say 'Mesarya' where the KTEB roster (duty_list) has used
-- 'Üst Mesarya' / 'Alt Mesarya' since 20261053. Each such row takes the ONE Mesarya
-- sub-region its name carries in duty_list (all dates, keyed by pharmacy_name_key, the
-- table's own PK function). A name under BOTH sub-regions, or NEITHER, keeps 'Mesarya':
-- no guess. Probed read-only 2026-10-04 (supabase/probe_mesarya_regions.sql): 18 rows,
-- 12 → Alt, 6 → Üst, 0 ambiguous. The assertions below hold that snapshot; a refusal means
-- the roster changed since — re-probe, do not loosen.
--
-- Some of these pharmacies also appear under Gazimağusa or Lefkoşa on past roster dates
-- (KTEB listing them with a nearby town). Those are not Mesarya sub-regions, so they do
-- not make a row ambiguous; none appears that way in the forward roster.
--
-- Only `region` changes. No policy, grant or coordinate is touched. The app's region gate
-- (utils/dutyFacilityMatch.js sameRegion) matches the new values exactly and keeps its
-- 'Mesarya' arm for any future bare row.

SET ROLE postgres;

BEGIN;

UPDATE public.pharmacy_coords c
   SET region = s.sub
  FROM (SELECT c2.name_key, min(d.region) AS sub
          FROM public.pharmacy_coords c2
          JOIN public.duty_list d ON public.pharmacy_name_key(d.name) = c2.name_key
         WHERE c2.region = 'Mesarya' AND d.region IN ('Üst Mesarya', 'Alt Mesarya')
         GROUP BY c2.name_key
        HAVING count(DISTINCT d.region) = 1) s
 WHERE c.name_key = s.name_key AND c.region = 'Mesarya';

-- ─── Assertions — any failure rolls back the whole file ──────────────────────
DO $$
DECLARE n int; names text; dist text;
BEGIN
  SELECT count(*), string_agg(name, ', ' ORDER BY name) INTO n, names
    FROM public.pharmacy_coords WHERE region = 'Mesarya';
  IF n <> 0 THEN RAISE EXCEPTION '20261080: % rows left as Mesarya (both or neither sub-region in duty_list): %', n, names; END IF;
  -- The whole distribution, derived and compared as one string: the two Mesarya counts AND
  -- every other region unchanged from 20261079's end state.
  -- COLLATE "C": prod's default collation is linguistic (İskele sorts with I), PGlite's is
  -- bytewise; the expected string is written in C order so it holds in both.
  SELECT string_agg(region || '=' || k, ', ' ORDER BY region COLLATE "C") INTO dist
    FROM (SELECT coalesce(region, 'NULL') AS region, count(*) AS k FROM public.pharmacy_coords GROUP BY 1) x;
  IF dist IS DISTINCT FROM 'Alt Mesarya=13, Gazimağusa=67, Girne=66, Güzelyurt=18, Karpaz=7, Lefke=10, Lefkoşa=130, Üst Mesarya=6, İskele=15' THEN
    RAISE EXCEPTION '20261080: region distribution is %', dist;
  END IF;
  -- Nothing but region moved: same rows, same pins, same sources as 20261079 left them.
  SELECT count(*) INTO n FROM public.pharmacy_coords;
  IF n <> 332 THEN RAISE EXCEPTION '20261080: % rows, expected 332', n; END IF;
  SELECT string_agg(coalesce(source, 'NULL') || ':' || verified || ':' || k, ', ' ORDER BY source COLLATE "C") INTO dist
    FROM (SELECT source, verified, count(*) FILTER (WHERE lat IS NOT NULL) AS k FROM public.pharmacy_coords GROUP BY 1, 2) x;
  IF dist IS DISTINCT FROM 'facilities:false:314, manual:true:14, NULL:false:0' THEN
    RAISE EXCEPTION '20261080: pinned rows by source/verified changed: %', dist;
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261080_pharmacy_coords_mesarya_split.sql', 'ff5a341afccb393175cce3b6a0d34d5154183dcb8c8538a16cc2270434a22777')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
