-- ─── towing_companies.is_active — invert the column DEFAULT to false ─────────
--
-- ⚠ THIS IS A DELIBERATE INVERSION OF THE CONVENTIONAL DEFAULT. Do not "fix" it back
--   as an oddity. Every other `is_active`-style flag in this schema defaults to true,
--   and for those tables that is right. For this one it is not, and here is why.
--
-- THE PROBLEM IT CLOSES
--   `search_content` (20260906) indexes any towing_companies row with is_active = true,
--   and it knows nothing about MODULE_FLAGS.towing. The flag gates the SCREEN only. So
--   an active row that exists before launch is publicly searchable while the module is
--   still dark: a user searches "çekici", finds a REAL firm, taps it, and lands on
--   Coming Soon. That is worse than not finding them — it teaches the user that ADA
--   cannot help with towing, and that is the lesson they still carry on the day they
--   actually break down.
--
--   Observed live on 2026-08-23: three review fixtures were returned to a signed-out
--   anon caller by search_content while MODULE_FLAGS.towing was false.
--
-- WHY A DEFAULT AND NOT JUST A CONVENTION
--   The seed template already carries a loud banner and an explicit `false` in its
--   VALUES. That protects the seeding path somebody has written. The DEFAULT protects
--   every path nobody has written yet — a future admin CRUD screen, a row hand-typed at
--   11pm, an import script, a fixture in a test. A convention holds until someone
--   forgets it; a default holds regardless.
--
--   The intended intermediate state for this table is "seeded, verified, NOT yet
--   launched". A default that publishes on omission makes the unsafe state the easy one.
--   This makes the safe state the easy one, and going live an explicit act.
--
-- WHAT IT DOES NOT DO
--   Nothing else changes: not the column type, not NOT NULL, not RLS, not any existing
--   row. `towing_select_public` still shows exactly the rows where is_active = true.
--   Rows already carrying an explicit value are untouched — a DEFAULT applies only when
--   INSERT omits the column.
--
-- BACKFILL: none needed. The table is empty of real firms; the only rows are the
-- inactive placeholder and any review fixtures, all of which set is_active explicitly.
--
-- GOING LIVE (Slice 3) is unchanged and is still one act in two places:
--   UPDATE towing_companies SET is_active = true WHERE slug <> 'ornek-cekici-test';
--   and MODULE_FLAGS.towing false -> true, plus the check-module-flags.mjs baseline.
--
-- Idempotent — SET DEFAULT is absolute, not relative, so re-running is a no-op.
-- SET ROLE postgres is REQUIRED: ALTER TABLE needs the table owner.

SET ROLE postgres;
BEGIN;

ALTER TABLE public.towing_companies ALTER COLUMN is_active SET DEFAULT false;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260907_towing_is_active_default_false.sql', 'f284f684eb3d7094e1a3c26a51808af70f65e5e301c05782966b79e9dd180f98')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- PostgREST caches column DEFAULTS as part of its schema cache, so a stale cache would
-- keep applying the old default to REST inserts even though Postgres has the new one.
-- Not an ADD COLUMN, but the same reload requirement applies.
NOTIFY pgrst, 'reload schema';

-- ─── Verification — ONE block, run after applying (Role = postgres) ──────────
-- Expect all four columns 'OK'. Nothing persists — the fixtures are rolled back.
--
-- BEGIN;
-- INSERT INTO public.towing_companies (name, slug, phone, base_region, coverage_regions, vehicle_classes)
-- VALUES ('Default probe','zz-default-probe','+90 000','nicosia',ARRAY['nicosia'],ARRAY['car']);
-- INSERT INTO public.towing_companies (name, slug, phone, base_region, coverage_regions, vehicle_classes, is_active)
-- VALUES ('Explicit probe','zz-explicit-probe','+90 000','nicosia',ARRAY['nicosia'],ARRAY['car'], true);
-- SELECT
--   (SELECT CASE WHEN column_default = 'false' THEN 'OK'
--                ELSE 'FAIL <- is ' || COALESCE(column_default,'NULL') END
--      FROM information_schema.columns
--     WHERE table_schema='public' AND table_name='towing_companies' AND column_name='is_active')
--     AS column_default_is_false,
--   -- the whole point: omitting the column must NOT publish the row
--   (SELECT CASE WHEN NOT is_active THEN 'OK' ELSE 'FAIL <- row published itself' END
--      FROM public.towing_companies WHERE slug='zz-default-probe')   AS omitted_lands_inactive,
--   -- and the default must not stomp an intentional true
--   (SELECT CASE WHEN is_active THEN 'OK' ELSE 'FAIL <- default overrode an explicit true' END
--      FROM public.towing_companies WHERE slug='zz-explicit-probe')  AS explicit_true_honoured,
--   -- nothing real is live yet (the probe above is the only expected active row)
--   (SELECT CASE WHEN count(*) = 0 THEN 'OK' ELSE 'FAIL <- ' || count(*) || ' unexpected live row(s)' END
--      FROM public.towing_companies WHERE is_active AND slug <> 'zz-explicit-probe')
--     AS no_live_firms_yet;
-- ROLLBACK;

-- ─── Rollback ────────────────────────────────────────────────────────────────
--   SET ROLE postgres;
--   ALTER TABLE public.towing_companies ALTER COLUMN is_active SET DEFAULT true;
--   RESET ROLE;
--   NOTIFY pgrst, 'reload schema';
--   DELETE FROM public.schema_migrations_applied WHERE filename = '20260907_towing_is_active_default_false.sql';
