-- ═══ duty_list — make a year-sized load safely repeatable ═══════════════════
--
-- WHY THIS LANDS BEFORE THE FORMAT IS DECIDED. KTEB are expected to supply a FULL-YEAR
-- roster around 2026-09-15: roughly 365 days × ~14 pharmacies ≈ 5,100 rows, against the
-- 414 rows one month took. Whatever shape that arrives in, it will be loaded in chunks,
-- and a chunked load is a load somebody re-runs — after a timeout, a disconnect, or
-- simply not being sure the third paste went through.
--
-- `duty_list` has NO unique constraint today. So a re-run does not fail, it DUPLICATES.
-- Silently. A year of health data, doubled, with every affected day showing each pharmacy
-- twice and no error anywhere to say so. DutyListScreen would render the duplicates as
-- separate entries because it groups by region and sorts by name — two identical rows
-- look like two pharmacies.
--
-- ⚠ THE CONSTRAINT IS WHAT MAKES THE LOAD IDEMPOTENT, and it must exist BEFORE the data
--   arrives. Adding it afterwards means first finding and deleting whatever duplicated,
--   which is exactly the archaeology this avoids.
--
-- ─── WHY (duty_date, name) AND NOT A SURROGATE ──────────────────────────────
--
-- The natural key is "this pharmacy, on this date". Two rows sharing it are the same
-- fact stated twice, never two facts. Region is not part of the key: a pharmacy sits in
-- exactly one region, so adding it would let the same pharmacy be inserted twice on one
-- date under two spellings of its region and defeat the point.
--
-- Once this exists the loader can use ON CONFLICT (duty_date, name) DO UPDATE, which
-- makes a re-run a no-op AND lets a corrected roster be re-applied over the top.
--
-- ─── THE INDEX QUESTION, ANSWERED RATHER THAN ASSUMED ───────────────────────
--
-- 20260719_add_missing_indexes.sql explicitly DECLINED an index here — "duty_list — no
-- confirmed query filter observed; not speculating." That was correct then. It is not
-- correct now: DutyListScreen.js filters `.eq('duty_date', today)` on every open, and
-- App.js now does the same for the banner's roster status. That is a confirmed filter.
--
-- 20260902_capture_schema_drift.sql recorded `duty_list_date_idx` as already existing in
-- the database. VERIFY THAT BEFORE LOADING 5,100 ROWS rather than trusting the record —
-- the verification block below has the query. The UNIQUE constraint creates its own
-- index on (duty_date, name), which also serves a duty_date-only lookup as a prefix, so
-- the separate index may turn out to be redundant. Do not drop it on that reasoning
-- without measuring; a redundant index on a 5,000-row table costs nothing worth having.
--
-- Apply by hand: SQL editor, Role = postgres. Then `node scripts/migration-ledger.mjs`
-- and re-run supabase/migration_ledger_check.sql.

SET ROLE postgres;
BEGIN;

-- ⚠ IF THIS FAILS, THE TABLE ALREADY HOLDS DUPLICATES. That is a finding, not an
--   obstacle: it would mean a past load ran twice. Do not force it — run the duplicate
--   query in the verification block first and decide what to keep.
--   (Today the table is EMPTY, so it cannot fail for that reason.)
ALTER TABLE public.duty_list
  DROP CONSTRAINT IF EXISTS duty_list_date_name_unique;
ALTER TABLE public.duty_list
  ADD CONSTRAINT duty_list_date_name_unique UNIQUE (duty_date, name);

COMMENT ON CONSTRAINT duty_list_date_name_unique ON public.duty_list IS
  'Natural key: one pharmacy, one date. Makes a chunked year-sized load idempotent via ON CONFLICT (duty_date, name) — without it a re-run silently duplicates a year of health data, and duplicates render as separate pharmacies.';

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20260920_duty_list_idempotent_load.sql', '4fd6dad866b0e1a641f0f2977788332546b6a0795ccbac96d73c883cfde10e24')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;

-- No ADD COLUMN, so no PostgREST cache reload is required: the schema cache holds
-- table/column shape, and a constraint changes neither.

-- ─── Verification (Role = postgres) ─────────────────────────────────────────
--   -- 1. the constraint exists:
--   SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
--    WHERE conrelid = 'public.duty_list'::regclass AND contype = 'u';
--   -- expect duty_list_date_name_unique UNIQUE (duty_date, name)
--
--   -- 2. DOES duty_list_date_idx ACTUALLY EXIST? 20260902 recorded it; confirm it.
--   SELECT indexname, indexdef FROM pg_indexes
--    WHERE schemaname = 'public' AND tablename = 'duty_list';
--   -- expect the primary key, duty_list_date_name_unique, and — if the record is
--   -- right — duty_list_date_idx on (duty_date).
--
--   -- 3. duplicates, if the ALTER ever refuses (it cannot today, the table is empty):
--   SELECT duty_date, name, count(*) FROM public.duty_list
--    GROUP BY 1,2 HAVING count(*) > 1 ORDER BY 3 DESC;
--
--   -- 4. WATCH IT REFUSE — a constraint nobody has seen reject something is a decoration:
--   BEGIN;
--     INSERT INTO public.duty_list (duty_date, name, region) VALUES ('2099-01-01','TEST ECZANESİ','Lefkoşa');
--     INSERT INTO public.duty_list (duty_date, name, region) VALUES ('2099-01-01','TEST ECZANESİ','Lefkoşa');
--   -- expect: duplicate key value violates unique constraint "duty_list_date_name_unique"
--   ROLLBACK;   -- leaves nothing behind, on a table users read

-- ─── Rollback ───────────────────────────────────────────────────────────────
--   SET ROLE postgres; BEGIN;
--   ALTER TABLE public.duty_list DROP CONSTRAINT IF EXISTS duty_list_date_name_unique;
--   DELETE FROM public.schema_migrations_applied WHERE filename = '20260920_duty_list_idempotent_load.sql';
--   COMMIT; RESET ROLE;
--   -- Dropping it re-opens the silent-duplication hole. Only do this if the natural key
--   -- turns out to be wrong — e.g. KTEB legitimately list one pharmacy twice on one date
--   -- with different hours — and replace it with a corrected key in the same session.
