-- ═══════════════════════════════════════════════════════════════════════════
-- 20261081 — supabase_read_only_user may run verify_schema QUERY 1
-- ═══════════════════════════════════════════════════════════════════════════
--
-- The supabase-migration-status workflow runs verify_schema.sql as supabase_read_only_user.
-- QUERY 1 CALLS two functions as behaviour tests (tokens 1035/1036: "false for a caller
-- with no session"), and the role holds EXECUTE on neither, so the whole report aborts
-- with 42501. Every other function QUERY 1 executes (search_fold, contains_blocked_term,
-- is_anonymous_session, auth.uid, auth.jwt) is already EXECUTE to PUBLIC.
--
-- WHY THIS GRANT CANNOT WRITE. Both functions are SECURITY DEFINER (they run as postgres),
-- so the role's own read-only-ness is not the argument. The argument is the bodies:
--   • may_initiate_by_age(uuid, uuid): STABLE plpgsql; SELECT … INTO locals, IF, RETURN.
--   • is_listed_student(uuid):          STABLE sql; one SELECT over student_education/profiles.
-- Both call only auth.uid() and is_anonymous_session() (STABLE sql, reads a GUC). And
-- Postgres refuses INSERT/UPDATE/DELETE inside a non-volatile SQL or plpgsql function, so
-- the STABLE marking is itself a guard; the DO block below fails if either becomes VOLATILE.
--
-- WHO CAN DO WHAT, after this: supabase_read_only_user can call these two functions. It
-- learns nothing new by doing so — it already bypasses RLS and can SELECT profiles and
-- student_education directly. anon and PUBLIC still cannot call either; authenticated
-- keeps its EXECUTE (the messaging path) unchanged. Nothing else changes.
--
-- Revoke: REVOKE EXECUTE ON FUNCTION public.may_initiate_by_age(uuid, uuid),
--   public.is_listed_student(uuid) FROM supabase_read_only_user;  (QUERY 1 then aborts again
--   under the status workflow; supabase-migrate's post-apply check runs as postgres and is
--   unaffected either way.)
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

GRANT EXECUTE ON FUNCTION public.may_initiate_by_age(uuid, uuid) TO supabase_read_only_user;
GRANT EXECUTE ON FUNCTION public.is_listed_student(uuid)         TO supabase_read_only_user;

DO $$
DECLARE
  v_fn   text;
  v_set  text;
  v_bad  int;
BEGIN
  FOREACH v_fn IN ARRAY ARRAY['public.may_initiate_by_age(uuid,uuid)', 'public.is_listed_student(uuid)'] LOOP
    -- The safety argument above, asserted: still DEFINER-with-pinned-path and still non-volatile.
    SELECT count(*) INTO v_bad FROM pg_proc
     WHERE oid = to_regprocedure(v_fn)
       AND (NOT prosecdef OR provolatile = 'v' OR COALESCE(proconfig::text, '') NOT ILIKE '%search_path=public%');
    IF v_bad > 0 OR to_regprocedure(v_fn) IS NULL THEN
      RAISE EXCEPTION '% is missing, VOLATILE, or not DEFINER with search_path=public — the grant''s safety argument no longer holds', v_fn;
    END IF;

    -- The full EXECUTE grantee set, derived and printed, never assumed.
    SELECT string_agg(CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE r.rolname END, ','
                      ORDER BY CASE WHEN a.grantee = 0 THEN 'PUBLIC' ELSE r.rolname END)
      INTO v_set
      FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a
      LEFT JOIN pg_roles r ON r.oid = a.grantee
     WHERE p.oid = to_regprocedure(v_fn) AND a.privilege_type = 'EXECUTE';
    IF v_set IS DISTINCT FROM 'authenticated,postgres,service_role,supabase_read_only_user' THEN
      RAISE EXCEPTION '% EXECUTE grantees are %, want authenticated,postgres,service_role,supabase_read_only_user', v_fn, coalesce(v_set, '(none)');
    END IF;

    -- Positive control: the role can now call it, and the app's path still works.
    IF NOT has_function_privilege('supabase_read_only_user', to_regprocedure(v_fn), 'EXECUTE')
       OR NOT has_function_privilege('authenticated', to_regprocedure(v_fn), 'EXECUTE') THEN
      RAISE EXCEPTION '% is not callable by supabase_read_only_user and authenticated', v_fn;
    END IF;
    -- Negative control: anon still cannot (no direct grant AND no inherited one).
    IF has_function_privilege('anon', to_regprocedure(v_fn), 'EXECUTE') THEN
      RAISE EXCEPTION '% is callable by anon', v_fn;
    END IF;
  END LOOP;

  -- The role is still read-only.
  IF has_table_privilege('supabase_read_only_user', 'public.notifications', 'INSERT')
     OR has_table_privilege('supabase_read_only_user', 'public.schema_migrations_applied', 'INSERT') THEN
    RAISE EXCEPTION 'supabase_read_only_user can INSERT — stop';
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261081_readonly_role_runs_verify_schema.sql', '715207d812695ab857f38093872136b2699b7308caef64978cc2a6a67c9a94d0')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
