-- ─── 20261067 — the ledger table documents how migrations are applied now ─────
--
-- From 2026-10-01 production migrations are applied ONLY by the supabase-migrate
-- workflow (.github/workflows/supabase-migrate.yml): no Mac holds a production
-- credential. This extends the ledger table's comment to say so. The 20260903 text is
-- kept word for word — it explains what a baseline row does and does not prove.
--
-- Also the first migration applied through that workflow, end to end: harmless by
-- construction (a COMMENT changes no data, no grant, no policy).
--
-- Who can read/write what: unchanged. A COMMENT grants nothing.
-- verify_schema.sql H token '1067_ledger_comment_supabase_migrate' asserts both halves.

SET ROLE postgres;

BEGIN;

COMMENT ON TABLE public.schema_migrations_applied IS
  'One row per applied migration. Baseline rows (applied_by = ''baseline'') assert only that the file matched live as of the 2026-08-19 drift audit, NOT that the file is what ran. Rows written after that are provenance: the migration stamped its own checksum at apply time. Compare against disk with supabase/migration_ledger_check.sql. Since 2026-10-01 migrations are applied only by the supabase-migrate GitHub Actions workflow (no Mac holds a production credential).';

DO $$
DECLARE c text := obj_description('public.schema_migrations_applied'::regclass, 'pg_class');
BEGIN
  IF c IS NULL OR c NOT LIKE '%supabase-migrate GitHub Actions workflow%' OR c NOT LIKE 'One row per applied migration.%Baseline rows%' THEN
    RAISE EXCEPTION '20261067: ledger comment is not the expected text: %', c;
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261067_ledger_comment_supabase_migrate.sql', 'f213880c5766d1ce22543b7dfc334bebfdb7db2ee47748b30b9dbbdb2700ae8a')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
