-- ═══════════════════════════════════════════════════════════════════════════
-- 20261075 — Live Scores: ask the provider which World competitions are current
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Ops call, no schema or data change. POSTs live-scores-football {mode:'leagues'}, which
-- spends ONE football request (/leagues?country=World&current=true) and returns the list in
-- its JSON log; pg_net keeps the response in net._http_response, where a read-only probe
-- reads it. The IDs chosen from that list are seeded by the next migration — never from
-- memory. A migration because the Vault service key is the only working caller (the CI
-- secret is refused by the function's service_role gate). pg_net sends after COMMIT.
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SELECT net.http_post(
  url     := 'https://jeihxnwqytnxtytgkzgf.supabase.co/functions/v1/live-scores-football',
  headers := jsonb_build_object('Content-Type', 'application/json', 'Authorization', 'Bearer ' ||
               (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'novest_sync_key')),
  body    := '{"mode":"leagues"}'::jsonb);

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261075_live_scores_league_lookup.sql', '74e444f4199e0ee6d5b563145790f68d580fa08c05b1848873875a750aa1a8bd')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
