-- ═══ institutions — Ankara Sosyal Bilimler's city confirmed (hand-applied) ═══════════
--
-- ALREADY APPLIED. Run by hand against production on 2026-09-15, Role = postgres, as the
-- single statement in section 2 — byte-for-byte, with no BEGIN/COMMIT of its own (the
-- transaction here is this file's, so the stamp can sit inside it). Sections 1 and 3 were
-- written afterwards and did NOT run in production.
--
-- …0017 Ankara Sosyal Bilimler Üniversitesi: city NULL → 'nicosia'. 20261021 left it NULL
-- deliberately because the district was unconfirmed. Owner confirmed: the campus is at
-- Haspolat Kavşağı, Gönyeli — Lefkoşa district. That agrees with the repo on both levels:
-- Gönyeli and Haspolat are nicosia areas in constants/areas.js, and constants/regions.js
-- anchors Gönyeli to nicosia.
--
-- ─── THIS IS THE EDIT 20261021's GUARD WAS WRITTEN FOR ───────────────────────
-- 20261021 now REFUSES to re-run: its ON CONFLICT DO UPDATE would set this city back to
-- NULL. Replaying the chain in order is unaffected (21 runs while the row is absent, then
-- this file). What its guard cannot stop is its bare recorded INSERT pasted on its own —
-- verify_schema.sql's 1023 token is what catches that.
--
-- ─── RE-RUN ──────────────────────────────────────────────────────────────────
-- A no-op against its own end state. Section 1 refuses if the row is missing (the UPDATE
-- would match 0 rows and succeed silently) or if its city has since moved to anything
-- other than NULL or 'nicosia' (a re-run would silently revert that later edit).
--
-- EXECUTION (only ever as a re-run): SQL editor, Role = postgres, the WHOLE FILE. No
-- NOTIFY — nothing here changes the schema.

SET ROLE postgres;

BEGIN;

-- ─── 1. Guard ────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_found boolean;
  v_city  text;
BEGIN
  SELECT true, city INTO v_found, v_city FROM public.institutions
   WHERE id = '00000000-0000-4000-b000-000000000017';
  IF v_found IS NULL THEN
    RAISE EXCEPTION 'REFUSING: …0017 does not exist, so 20261021 has not run here and the UPDATE would match 0 rows. Nothing applied.';
  END IF;
  IF v_city IS NOT NULL AND v_city IS DISTINCT FROM 'nicosia' THEN
    RAISE EXCEPTION 'REFUSING: …0017 city is now "%" — edited after this file ran; re-running would revert it to nicosia. Nothing applied.', v_city;
  END IF;
  RAISE NOTICE '…0017 city before: %', coalesce(v_city, 'NULL');
END $$;

-- ─── 2. RECORDED — as run by hand against production, 2026-09-15 (verbatim) ───
UPDATE institutions SET city = 'nicosia'
WHERE id = '00000000-0000-4000-b000-000000000017';
-- ─── END RECORDED ───────────────────────────────────────────────────────────

-- ─── 3. State check — this file's end state ─────────────────────────────────
DO $$
DECLARE
  v_city     text;
  v_active   boolean;
  v_nullcity text;
BEGIN
  SELECT city, is_active INTO v_city, v_active FROM public.institutions
   WHERE id = '00000000-0000-4000-b000-000000000017';
  IF v_city IS DISTINCT FROM 'nicosia' OR v_active IS DISTINCT FROM true THEN
    RAISE EXCEPTION '…0017 city = %, is_active = % — expected nicosia, true',
      coalesce(v_city, 'NULL'), coalesce(v_active::text, '<row missing>');
  END IF;

  -- Printed, not asserted: it describes rows this file did not touch. A city-less active
  -- university is hidden under every region chip in the Student Hub directory, and ASBÜ
  -- was the only one; Other (…00ff) is excluded from that directory.
  SELECT string_agg(name, ', ' ORDER BY name) INTO v_nullcity FROM public.institutions
   WHERE is_active AND city IS NULL AND id <> '00000000-0000-4000-b000-0000000000ff';
  RAISE NOTICE '…0017 city = nicosia. Active universities still without a city: %', coalesce(v_nullcity, 'none');
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261023_institutions_asbu_city.sql', 'c23543884716562bb82c6306c777603123e67b6b8856bfc426176d3690d70407')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
