-- ═══════════════════════════════════════════════════════════════════════════
-- 20261076 — opening hours for AKDENİZ ECZANESİ (Atatürk Caddesi, Yenişehir, Lefkoşa)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- The first facility with hours (0 of 393 live had any on 2026-10-04), and the Şimdi açık
-- test case for fix/open-now-json. One row: 8396e795-fb07-4fc8-bba8-c05359d76463.
--
-- Source: Berke, 2026-10-04 (his wife's pharmacy) — the real hours, shown to all users:
--   Mon–Fri 08:00–17:30 (no lunch break) · Sat 08:00–13:30 · Sun closed
--
-- Written EXACTLY as components/HoursPicker.js buildOutput() writes it, so this tests the
-- path providers will use: JSON.stringify of {Day: {o, c}} in DAYS order (Mon…Sun), closed
-- days absent, no spaces. utils/facilityUtils.js parseIsOpen reads it (scripts/
-- test-open-now.mjs carries this exact string). Duty nights (next: 2026-11-09, 08:00 →
-- 00:00) are handled in the app from duty_list, not here.
--
-- Apply: supabase-migrate (dry run, then apply=true). Re-runnable: a second run finds the
-- same value and changes nothing. It REFUSES to overwrite hours that differ — replacing
-- hours somebody else entered is a bigger act than this file.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  c_id    constant uuid := '8396e795-fb07-4fc8-bba8-c05359d76463';
  c_hours constant text := '{"Mon":{"o":"08:00","c":"17:30"},"Tue":{"o":"08:00","c":"17:30"},"Wed":{"o":"08:00","c":"17:30"},"Thu":{"o":"08:00","c":"17:30"},"Fri":{"o":"08:00","c":"17:30"},"Sat":{"o":"08:00","c":"13:30"}}';
  v_n     int;
  v_cur   text;
  v_bad   text;
BEGIN
  -- Exactly one row, by id AND name AND type.
  SELECT count(*) INTO v_n FROM public.facilities
   WHERE id = c_id AND name = 'AKDENİZ ECZANESİ' AND type = 'pharmacy';
  IF v_n IS DISTINCT FROM 1 THEN
    SELECT string_agg(format('%s|%s|%s', id, name, type), '; ') INTO v_bad
      FROM public.facilities WHERE id = c_id OR name LIKE '%AKDEN%';
    RAISE EXCEPTION 'expected exactly 1 row (id+name+type), matched %. Read: %', v_n, coalesce(v_bad, '(nothing)');
  END IF;

  -- The value is the shape the picker writes: an object of the six open days, each {o, c}.
  IF (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(c_hours::jsonb) k)
     IS DISTINCT FROM ARRAY['Fri','Mon','Sat','Thu','Tue','Wed'] THEN
    RAISE EXCEPTION 'hours literal is not the six open days: %', c_hours;
  END IF;

  SELECT opening_hours INTO v_cur FROM public.facilities WHERE id = c_id;
  IF v_cur IS NOT NULL THEN
    IF v_cur IS DISTINCT FROM c_hours THEN
      RAISE EXCEPTION 'already has different hours, not overwriting: %', v_cur;
    END IF;
    RETURN;  -- re-run: identical value already in place
  END IF;

  UPDATE public.facilities SET opening_hours = c_hours WHERE id = c_id;

  -- Read back, byte for byte.
  SELECT opening_hours INTO v_cur FROM public.facilities WHERE id = c_id;
  IF v_cur IS DISTINCT FROM c_hours THEN
    RAISE EXCEPTION 'read-back differs: %', coalesce(v_cur, 'NULL');
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261076_akdeniz_opening_hours.sql', 'ad8f1c478ac7d533627c5fbf4a0baade2dd8f3a87be943ba5d34afe145299c0e')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
