-- ═══════════════════════════════════════════════════════════════════════════
-- 20261090 — Live Scores: pause the six API-Sports cron jobs (account suspended)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- API-Sports has refused every request since 2026-10-04 15:24 UTC ("Your account is
-- suspended"). Berke, 2026-10-06: pause Live Scores, keep everything else. So the six jobs
-- from 20261072 are set INACTIVE — not unscheduled — so re-enabling is one statement per job
-- (below) and the jobs keep their Vault-key commands unchanged.
--
-- KEPT: every live-scores table and its data, the three Edge Functions, the KTFF editor
-- (live_score_editors), the publication and all policies. LIVE_SCORES_LIVE stays false.
-- Data only; no named object changes. verify_schema QUERY 2 stops expecting these six jobs
-- active (they are listed as paused there, so a re-enable is a deliberate edit).
--
-- Re-enable (when a provider is back):
--   SELECT cron.alter_job(jobid, active := true) FROM cron.job WHERE jobname LIKE 'live-scores-%';
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  r       record;
  v_names text;
  v_n     int;
BEGIN
  SELECT count(*) INTO v_n FROM cron.job WHERE jobname LIKE 'live-scores-%';
  IF v_n IS DISTINCT FROM 6 THEN
    RAISE EXCEPTION 'expected the 6 live-scores jobs from 20261072; found %', v_n;
  END IF;
  FOR r IN SELECT jobid FROM cron.job WHERE jobname LIKE 'live-scores-%' LOOP
    PERFORM cron.alter_job(r.jobid, active := false);
  END LOOP;
  SELECT count(*), string_agg(jobname, ', ' ORDER BY jobname) INTO v_n, v_names
    FROM cron.job WHERE jobname LIKE 'live-scores-%' AND active;
  IF v_n IS DISTINCT FROM 0 THEN
    RAISE EXCEPTION 'live-scores jobs still active after the pause: %', v_names;
  END IF;
  -- Nothing else touched: the job commands are the same six (still Vault-keyed, no inline key).
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname LIKE 'live-scores-%'
              AND (command LIKE '%eyJ%' OR command NOT LIKE '%novest_sync_key%')) THEN
    RAISE EXCEPTION 'a live-scores job command changed shape';
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261090_live_scores_pause_cron.sql', '808dbb0bd62831cc7e42d4b726f83389bb1e0d4e02675049661c1915240e277a')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
