-- ═══ institutions — the TRNC ASBÜ row is named as its campus ═══════════════════════════
--
-- Row …0017 is Ankara Sosyal Bilimler Üniversitesi's Lefkoşa campus (kktc.asbu.edu.tr). Since
-- 20261096/99 the university itself (YÖK, Ankara) is also listed, under the identical name, so
-- anywhere a name shows without its country (a profile, a student card) the two could not be
-- told apart. The campus takes its campus name, the pattern of ODTÜ Kuzey Kıbrıs Kampüsü and
-- İTÜ-KKTC Eğitim Araştırma Yerleşkeleri (decided by Berke 2026-10-09).
--
-- Nobody is affected: live 2026-10-09 (readonly asbu_picks), student_education — the only
-- table referencing institutions — has 0 rows at either ASBÜ row. A data change only; the id,
-- and so every reference, is unchanged.
--
-- RE-RUN: a no-op once renamed. Refuses anything else it finds.
-- EXECUTION: supabase-migrate workflow (dry, then -f apply=true).

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  c_id  constant uuid := '00000000-0000-4000-b000-000000000017';
  c_old constant text := 'Ankara Sosyal Bilimler Üniversitesi';
  c_new constant text := 'Ankara Sosyal Bilimler Üniversitesi KKTC Yerleşkesi';
  v_name    text;
  v_country text;
  v_n       int;
BEGIN
  SELECT name, country INTO v_name, v_country FROM public.institutions WHERE id = c_id;
  IF v_country IS DISTINCT FROM 'XN' OR v_name IS NULL OR v_name NOT IN (c_old, c_new) THEN
    RAISE EXCEPTION 'REFUSING: …0017 is name=% country=%, expected the TRNC ASBÜ row. Nothing applied.', v_name, v_country;
  END IF;
  SELECT count(*) INTO v_n FROM public.institutions WHERE country = 'XN' AND name = c_new AND id <> c_id;
  IF v_n > 0 THEN
    RAISE EXCEPTION 'REFUSING: another TRNC row already carries "%". Nothing applied.', c_new;
  END IF;

  UPDATE public.institutions SET name = c_new WHERE id = c_id AND country = 'XN' AND name = c_old;

  SELECT count(*) INTO v_n FROM public.institutions WHERE country = 'XN' AND name = c_new AND id = c_id;
  IF v_n IS DISTINCT FROM 1 THEN
    RAISE EXCEPTION 'rename did not land on …0017 (% rows) — rolled back', v_n;
  END IF;
  SELECT count(*) INTO v_n FROM public.institutions WHERE country = 'XN' AND name = c_old;
  IF v_n IS DISTINCT FROM 0 THEN
    RAISE EXCEPTION 'a TRNC row still carries "%" (% rows) — rolled back', c_old, v_n;
  END IF;
  SELECT count(*) INTO v_n FROM public.institutions WHERE name = c_old;
  RAISE NOTICE 'rows still named "%" (the YÖK Ankara row, if seeded): %', c_old, v_n;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261101_institutions_asbu_campus_name.sql', '323e3fa260fb202c97b8323eb80cccce6d2105b76cc3387bb5d2f5300931a741')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
