-- ═══════════════════════════════════════════════════════════════════════════
-- 20261086 — iOS soft update notice for 1.3.0 (store-update popup, 20261051)
--
-- latest_version → '1.3.0' on iOS ONLY: 1.2.0 installs get the dismissible "New version available".
-- min_supported_version STAYS '1.0.0' (blocks nobody; raising it needs the force-tier device pass on
-- both platforms — CLAUDE.md). Applied after Apple approved 1.3.0 (READY_FOR_DISTRIBUTION, confirmed
-- via the ASC API 2026-10-06). Android was set by 20261082 and must stay 1.3.0 / 1.0.0.
-- Guarded on the current value, so a re-run changes nothing and the assertion says why.
-- ═══════════════════════════════════════════════════════════════════════════
SET ROLE postgres;
BEGIN;
SET LOCAL lock_timeout = '5s';

UPDATE public.app_versions
   SET latest_version = '1.3.0', updated_at = now()
 WHERE platform = 'ios' AND latest_version = '1.2.0';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.app_versions
                  WHERE platform = 'ios' AND latest_version = '1.3.0' AND min_supported_version = '1.0.0') THEN
    RAISE EXCEPTION 'app_versions ios: expected latest 1.3.0 with min_supported still 1.0.0';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.app_versions
                  WHERE platform = 'android' AND latest_version = '1.3.0' AND min_supported_version = '1.0.0') THEN
    RAISE EXCEPTION 'app_versions android: expected unchanged (latest 1.3.0, min 1.0.0)';
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261086_app_versions_ios_latest_130.sql', '7c6335c6397105dc9492269e87df667702c31f28336257bd83066eeea73e78fb')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
