-- ═══════════════════════════════════════════════════════════════════════════
-- 20261073 — Live Scores: the first (and only) score editor
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Grants Berke's own CUSTOMER account the score-editor membership (Berke, 2026-10-03:
-- "grant only my account, nobody else for now"). A customer, not his admin account: an
-- admin never reaches Home, and an admin is never a test identity (CLAUDE.md). With this
-- row the account
--   • may enter KTFF fixtures and live scores (20261070's editor policies, manual rows only);
--   • sees the Live Scores tile while LIVE_SCORES_LIVE is false — App.js asks
--     is_score_editor() and unlocks that one tile for this user alone.
--
-- Referenced by user id only. This repository is public; an id is not a credential and
-- names nobody, whereas an email would. The DO block asserts the id is a real, non-guest,
-- non-admin account before anything is written.
--
-- WHO CAN DO WHAT: unchanged policies. live_score_editors is still writable by no client;
-- this row is the whole of the change. Revoke: DELETE FROM public.live_score_editors
-- WHERE user_id = '412cad91-2e3b-41b9-8186-175dfb8afa35';
-- ═══════════════════════════════════════════════════════════════════════════

SET ROLE postgres;

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
DECLARE
  v_uid  uuid := '412cad91-2e3b-41b9-8186-175dfb8afa35';
  v_role text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = v_uid AND NOT coalesce(is_anonymous, false)) THEN
    RAISE EXCEPTION 'editor account % is missing or anonymous', v_uid;
  END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = v_uid;
  IF v_role IS DISTINCT FROM 'customer' THEN
    RAISE EXCEPTION 'editor account % has role % (want customer: admins never reach Home)', v_uid, v_role;
  END IF;
END $$;

INSERT INTO public.live_score_editors (user_id)
VALUES ('412cad91-2e3b-41b9-8186-175dfb8afa35')
ON CONFLICT (user_id) DO NOTHING;

-- The full membership is exactly this one account. A second editor is a decision with its
-- own migration, and the verify_schema token makes that edit the review moment.
DO $$
DECLARE v_set text;
BEGIN
  SELECT string_agg(user_id::text, ',' ORDER BY user_id) INTO v_set FROM public.live_score_editors;
  IF v_set IS DISTINCT FROM '412cad91-2e3b-41b9-8186-175dfb8afa35' THEN
    RAISE EXCEPTION 'live_score_editors should be exactly the one granted account; is %', coalesce(v_set, '(empty)');
  END IF;
END $$;

-- ─── ledger:stamp:begin ──────────────────────────────────────────────
-- Machine-generated by scripts/migration-ledger.mjs --stamp. Do not hand-edit.
-- The checksum is of THIS FILE WITH THIS BLOCK STRIPPED, which is what lets the file
-- carry its own stamp. Everything between the markers is excluded from the checksum
-- but still runs — so it may contain NOTHING but this INSERT. See the note in the
-- generator: anything else here would execute on paste while leaving no trace in the
-- hash, and the ledger would be attesting a file it never actually verified.
--
-- This is also the LAST statement inside BEGIN/COMMIT: if a paste is truncated before
-- it, COMMIT is never reached and nothing applies.
INSERT INTO public.schema_migrations_applied (filename, checksum)
VALUES ('20261073_live_scores_editor_grant.sql', 'dc83db26be50c34d7371696ff9a3ef2ce9a758ba1329a415d72ad616a7611f4b')
ON CONFLICT (filename) DO UPDATE
  SET checksum = excluded.checksum, applied_at = now(), applied_by = current_user;
-- ─── ledger:stamp:end ────────────────────────────────────────────────
COMMIT;
RESET ROLE;
